### ISSUE TITLE
clarify rotated/unrotated mesh files

### ISSUE THREAD

**Issue by chrisdane** [FESOM/fesom2#1]
Hi FESOM team

A wish: is there a way to clarify the rotated versus unrotated mesh mysterium of the fesom1.4 meshes? For example:
```
$ head -3 /pool/data/AWICM/FESOM1/MESHES/core/nod2d.out
  126859
       1 110.883650498 -66.1483566126        1
       2 257.574958343 -74.2146210526        1
```
versus
```
$ head -3 /work/bm0944/input/CORE2_final/nod2d.out
 126859
 1 117.9772 -77.1266 1
 2 -33.0436 -63.7543 1
```
For the users it is unclear which mesh to use. The two options
```
rotated_grid=.true. 	  	!option only valid for coupled model case now
force_rotation=.true.		!set to .true. for some unrotated meshes
```
actually increase confusion.

I dont know if the FESOM2 meshes are organized in a different way but if they are, I would be very happy if this gets more clear.

Thanks!
Chris

**Comment by koldunovn** [comment]
Dear Chris, 

Having rotated and unrotated meshes indeed cause a lot of confusion, unfortunately. FESOM2 still use both, but we will try to get rid of rotated meshes entirely. We will also try to make it more clear in the documentation.

**Comment by pgierz** [comment]
I also would very much appreciate more clarity here. It will make my bug hunts shorter ;-)

**Comment by koldunovn** [comment]
We agreed on moving to the unrotated meshes,  but for the time being there are two mechanisms to decrease confusion:

- It's currently not possible to use mesh with the wrong `force_rotation` flag, model will return an error.
- It's planned to have a flag in global attributes, that will define what setting for `force_rotation` used in the model, so post processing can try to look at this flag and decide what angles to use #19 

I will close this issue, but feel free to reopen it, if you feel it's not solved.
