### ISSUE TITLE
Do we sse the new issue in slack?

### ISSUE THREAD

**Issue by koldunovn** [FESOM/fesom2#12]
Test issue to see if slack connection is working.

**Comment by pgierz** [comment]
Is there a fesom slack? Perhaps this can be advertised on the website or in the readme file.

**Comment by JanStreffing** [comment]
Its on the climate dynamics slack. We can invite core devs from the paleoclimate section though.
Native cross workspace channels are only included in the entersprise edition of slack.

**Comment by koldunovn** [comment]
Slack is quite expensive, I don't think we will pay for the enterprise edition. What we can do is to try to connect FESOM2 github to paleo Slack channel, as we did for climate dynamics. Maybe you can try and let me know what permissions are nessesary for you to do so.

But at the end of the day our Slack channel mainly used for notifying that something is going on in the repository. I would prefer all conversations to happen on GitHub, so that we have an archive to refer to :) Messages in Slack (free version) are deleted after a while.

**Comment by JanStreffing** [comment]
For now I invited some paleoclimate members as guests to our fesom, pyfesom and awicm3 channels. I think this is an acceptable solution for the size of the project. No need to pay for anything :)

**Comment by koldunovn** [comment]
I think we can close it for now :)

**Comment by pgierz** [comment]
Test re-open to see if it pops up in paleo group (sorry Nikolay)
