### ISSUE TITLE
Fesomstandalone error message

### ISSUE THREAD

**Issue by dchari** [FESOM/fesom2#127]
I got this error message in simulating fesomstandlone. 
'''
>
> The error I got was basically:
0:  Reading restart: timestamps in restart and in clock files do not match
  0:  restart/ times are:   31534200.0000000       6.267617970012885E-319
  0:  the model will stop!
  0:  error counter=           2
  0:  Error: 
  0:  NetCDF: Index exceeds dimension bound 
The path to my experiment  is "/work/ba1006/a270151/esm-experiments/core/ scripts/"...
> the version is fesom2.0.
>  "cdo    settime: Open failed on >/work/ba1006/a270151/esm-experiments//core/restart/fesom//fesom.1947.oce.restart.nc<
>                 No such file or directory"
'''

**Comment by koldunovn** [comment]
@dchari I see that already have renamed restarts in your directory. However you are trying to use restart with `1948-01-31 23:30:00` as a date. If you want to start from the year 1949, and `fesom.clock`
```
84600 365 1948
0.0000000000000 1 1949
```
you need 1948 restart with the time stamp '1948-12-31 23:30:00' in it.
