### ISSUE TITLE
Sea ice accumulation in Canadian Archipelago

### ISSUE THREAD

**Issue by PengyangSong** [FESOM/fesom2#129]
Dear model developers,
I found my control run has sea ice thickness>40m over five COREII cycles.

In the first cycle, sea ice thickness reaches 20m, at below red points, 
![1](https://user-images.githubusercontent.com/72070671/118817556-a1508e80-b8b3-11eb-8d80-eb7ce705f46c.png)

The time series of SIC and SIT at these mesh nodes looks like this:
![2](https://user-images.githubusercontent.com/72070671/118817733-d52bb400-b8b3-11eb-89e6-041e4ae8b73b.png)

The code is in:
/home/ollie/psong/bug_report/calc_seaice_series.ipynb

I think this is caused by the semiclosed area, low resolution, and shallow water depth (only 30m).
But I am still curious about if it is solvable in the CORE mesh.

**Comment by qiangclimate** [comment]
Hi Pengyang，
this is a kind of "simulation feature" in such fjords, associated with winds accumulating sea ice. One might reduce the magnitudes slightly (like within 20m) by changing ice strength parameters. However, the impact of the parameters on sea ice in all other places is also large and their adjustment should not be for such fjords. As these small areas do not influence the overall sea ice budget and model stability, one could ignore the issue. Such fjords are sometimes just eliminated on meshes in some models, which could be an option too.
