### ISSUE TITLE
fesom release 2.1 via esm_tools

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#141]
I would like to make simulations that compare fesom release 2.1 with the latest awicm3. Are there any plans to implement release 2.1 into the esm_tools? I'm quite used to the esm_tool now, but when installing fesom2 I get tag: 2.0.2 from 2018.

Or do I need some branch of the esm_tools?

Cheers, Jan

**Comment by koldunovn** [comment]
Hi Jan, 

I made an attempt to do this in this branch https://github.com/esm-tools/esm_tools/tree/nk/fesom2.1_standalone , but it has some problems with job resubmissions in standalone mode, so not merged yet. I will not be able to come back to it before July 22. Although it can be a starting point if you would like to play around, as most of the necessary things should be there I guess.

**Comment by koldunovn** [comment]
Was merged in ESM-Tools https://github.com/esm-tools/esm_tools/pull/417
