### ISSUE TITLE
awicm-3-frontiers branch does not compile (gfortran 10.2)

### ISSUE THREAD

**Issue by hegish** [FESOM/fesom2#148]
```
src/io_meandata.F90:520:109:

  520 |         call def_stream(nod2D,  myDim_nod2D,  'subli', 'sublimation',                   'm/s',  sublimation(:),   1, 'm',  i_real4,  mesh)
      |                                                                                                             1
Error: Syntax error in argument list at (1)```

**Comment by JanStreffing** [comment]
I saw this yesterday. I found that the intel compiler does not have a problem. I compiled and ran a simulations where I had sublimation output too. I had a quick chat the Nikolay about this:

> N: On ollie the Intel compiler used by default, tests use gfortran, which is much more strict. I would search for non ASCII characters maybe?
> J: I don't see anything like that.
> N: I don’t think it’s tests, anyway :slightly_smiling_face: I would try to experimenting with this line and see if error will change. Every commit will trigger the tests now. You can run tests locally with docker https://github.com/FESOM/FESOM2_Docker/tree/master/fesom2_test  While you need slightly different version for docker image : koldunovn/fesom2_test:unrot
> `docker run -it  koldunovn/fesom2_test:unrot /bin/bash`

**Comment by hegish** [comment]
I looked into it and I think sublimation is only declared if __oasis is defined. Please see my commit 6ab6f510

**Comment by JanStreffing** [comment]
Ah, yes. That's why it worked for me.. Thanks for the fix!
