### ISSUE TITLE
missing lat, lon fields in fesom.mesh.diag.nc

### ISSUE THREAD

**Issue by suvarchal** [FESOM/fesom2#152]
To make fesom.mesh.diag.nc an efficient replacement for inferring mesh info in analysis compared to current text files (nod2d.out...), it should include lat(nod2), lon(nod2) information.

is `zbar_n_bottom` in fesom.mesh.diag.nc same as topography information in aux3d.out? if so just having lat, lon info would make mesh diag complete replacement else the topo data should also be included.

**Comment by koldunovn** [comment]
The coordinates can be extracted from `nodes`, one just have to convert them from radians.

The topography information from `aux3d.out` is never used in the model directly. It is used to generate model topography, that can only be as coarse in vertical as the vertical levels. So one should use topography from aux3d.out only in very special cases.

Any computations should be done only with `zbar_e_bottom` or `zbar_n_bottom`.

At the end of the day it's not that hard just to output `lon, lat` in degrees. Maybe you can try to implement it yourself as way to get to know FESOM2 a bit better? :)

**Comment by helgegoessling** [comment]
I see that'd you like to have everything in just one "standard" file ... but just in case it might still be useful, I think that information should be contained in the (CDO-readable) "griddes" files, e.g., on Mistral:

> ncdump -h /pool/data/AWICM/FESOM2/MESHES_FESOM2.1/core2/core2_griddes_nodes.nc
netcdf core2_griddes_nodes {
dimensions:
	ncells = 126858 ;
	vertices = 18 ;
	nlinks_max = 9 ;
	Three = 3 ;
	ntriags = 244659 ;
	nlev = 47 ;
	nlev_bnds = 48 ;
variables:
	double lon(ncells) ;
		lon:units = "degrees_east" ;
		lon:standard_name = "longitude" ;
		lon:bounds = "lon_bnds" ;
	double lon_bnds(ncells, vertices) ;
		lon_bnds:units = "degrees_east" ;
		lon_bnds:standard_name = "longitude_bounds" ;
		lon_bnds:centers = "lon" ;
	double lat(ncells) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:bounds = "lat_bnds" ;
	double lat_bnds(ncells, vertices) ;
		lat_bnds:units = "degrees_north" ;
		lat_bnds:standard_name = "latitude_bounds" ;
		lat_bnds:centers = "lat" ;
	double cell_area(ncells) ;
		cell_area:units = "m2" ;
		cell_area:_FillValue = -1. ;
		cell_area:long_name = "area of grid cell" ;
		cell_area:grid_type = "unstructured" ;
		cell_area:coordinates = "lat lon" ;
	int node_node_links(ncells, nlinks_max) ;
		node_node_links:_FillValue = -1 ;
		node_node_links:long_name = "Indicates which other nodes neighbour each node." ;
	int triag_nodes(ntriags, Three) ;
		triag_nodes:_FillValue = -1 ;
		triag_nodes:long_name = "Maps every triangular face to its three corner nodes." ;
	int coast(ncells) ;
		coast:_FillValue = -1 ;
		coast:long_name = "Indicates coastal nodes: coast=1, internal=0" ;
		coast:grid_type = "unstructured" ;
		coast:coordinates = "lat lon" ;
	double depth(nlev) ;
		depth:units = "m" ;
		depth:_FillValue = -1. ;
		depth:long_name = "depth of model levels in metres (positive downwards)" ;
	double depth_bnds(nlev_bnds) ;
		depth_bnds:units = "m" ;
		depth_bnds:_FillValue = -1. ;
		depth_bnds:long_name = "depth of model level bounds in metres (positive downwards)" ;
	int depth_lev(ncells) ;
		depth_lev:_FillValue = -1 ;
		depth_lev:long_name = "depth in terms of number of active levels beneath each ocean surface grid point" ;
		depth_lev:grid_type = "unstructured" ;
		depth_lev:coordinates = "lat lon" ;

// global attributes:
		:Conventions = "CF-1.4" ;
		:history = "2020-10-14 06:20:34 GMT; Grid description file generated with spheRlab version 1.1.5; Grid read and converted with: sl.grid.readFESOM(griddir = grd.paths[i]); Grid written with: sl.grid.writeCDO(grd, paste0(out.path, \"/\", grd.names[i], \"_griddes_nodes.nc\"), overwrite = TRUE, ofile.ZAXIS = NULL)" ;
}

> ncdump -h /pool/data/AWICM/FESOM2/MESHES_FESOM2.1/core2/core2_griddes_elements.nc
netcdf core2_griddes_elements {
dimensions:
	ntriags = 244659 ;
	Three = 3 ;
	nlinks_max = 9 ;
	ncells = 126858 ;
	nlev = 47 ;
	nlev_bnds = 48 ;
variables:
	double lon(ntriags) ;
		lon:units = "degrees_east" ;
		lon:standard_name = "longitude" ;
		lon:bounds = "lon_bnds" ;
	double lon_bnds(ntriags, Three) ;
		lon_bnds:units = "degrees_east" ;
		lon_bnds:standard_name = "longitude_bounds" ;
		lon_bnds:centers = "lon" ;
	double lat(ntriags) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:bounds = "lat_bnds" ;
	double lat_bnds(ntriags, Three) ;
		lat_bnds:units = "degrees_north" ;
		lat_bnds:standard_name = "latitude_bounds" ;
		lat_bnds:centers = "lat" ;
	double cell_area(ntriags) ;
		cell_area:units = "m2" ;
		cell_area:_FillValue = -1. ;
		cell_area:long_name = "area of grid cell" ;
		cell_area:grid_type = "unstructured" ;
		cell_area:coordinates = "lat lon" ;
	int node_node_links(ncells, nlinks_max) ;
		node_node_links:_FillValue = -1 ;
		node_node_links:long_name = "Indicates which other nodes neighbour each node." ;
	int triag_nodes(ntriags, Three) ;
		triag_nodes:_FillValue = -1 ;
		triag_nodes:long_name = "Maps every triangular face to its three corner nodes." ;
	int coast(ntriags) ;
		coast:_FillValue = -1 ;
		coast:long_name = "Indicates coastal triangles: coast=1, internal=0" ;
		coast:grid_type = "unstructured" ;
		coast:coordinates = "lat lon" ;
	double depth(nlev) ;
		depth:units = "m" ;
		depth:_FillValue = -1. ;
		depth:long_name = "depth of model levels in metres (positive downwards)" ;
	double depth_bnds(nlev_bnds) ;
		depth_bnds:units = "m" ;
		depth_bnds:_FillValue = -1. ;
		depth_bnds:long_name = "depth of model level bounds in metres (positive downwards)" ;
	int depth_lev(ntriags) ;
		depth_lev:_FillValue = -1 ;
		depth_lev:long_name = "depth in terms of number of active levels beneath each ocean surface element" ;
		depth_lev:grid_type = "unstructured" ;
		depth_lev:coordinates = "lat lon" ;

// global attributes:
		:Conventions = "CF-1.4" ;
		:history = "2020-10-14 06:20:34 GMT; Grid description file generated with spheRlab version 1.1.5; Grid read and converted with: sl.grid.readFESOM(griddir = grd.paths[i]); Grid written with: sl.grid.writeCDO(grd, paste0(out.path, \"/\", grd.names[i], \"_griddes_elements.nc\"), fesom2velocities = T, overwrite = TRUE, ofile.ZAXIS = NULL)" ;
}

**Comment by suvarchal** [comment]
@helgegoessling  your griddes is beautiful, I suppose those were generated using something like: [data_processing](https://fesom2.readthedocs.io/en/latest/data_processing/data_processing.html)?

Here is my angle:  to have efficient data processing pipelines for HR simulations, uncompressed text files like nod2d.out are pretty inefficient to deal with (will some what need to load all the text files into memory), meanwhile netcdf/hdf-like metadata aware binary formats are better way to deal with.

I am not sure if this mesh diag file is a passive file or is actively used elsewhere like restart or some other workflow. If not, **i think**,  having it in cdo friendly format is certainly advantageous by reducing a post processing step on the users or may be even more standardized(?)  [UGRID](http://ugrid-conventions.github.io/ugrid-conventions/) format.
