### ISSUE TITLE
Automatically initializing missing fields when restarting with different configuration

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#157]
When changing FESOM2 configurations between restarts, e.g.
```
FESOM2 standalone 0_layer -> AWICM3 0_layer
FESOM2 standalone 0_layer -> FESOM2 standalone Icepack
AWICM3 0_layer -> AWICM3 Icepack
```
We run into the situation that the restart files written by the previous configuration do not cover all the required restart fields of the new configuration. In the past I added the missing fields with some initial values via cdo. This is not good practice, since cdo will make new files with arbitrary dimension ordering, which can make reading the files very slow on some machines.

A much better solution would be to catch the missing restart file (talking about the new netcdf parallel restarts by @hegish here where each field has its own file) and if the restart file is not there, to initialize the field with appropriate values.

The first practical application would be @tsemmler05 using a D3 standalone restart for a TCO319L137-D3 coupled simulation. The missing fields would be `ice_albedo=0.75` and `ice_temp=273.15`

@hegish can you point towards an appropriate branch to develop this feature from?

**Comment by hegish** [comment]
I am not sure if I understand this correctly, but does this not belong to the setup of an experiment, i.e. outside of Fesom?

**Comment by JanStreffing** [comment]
I had discussed this before with @dsidoren and he thought it would be easier to handle inside fesom2 because you need no external tools.

**Comment by hegish** [comment]
As we do not know when these features will be merged with master, I would suggest branching this feature either from awicm-3-frontiers_parallel-restart, which is as similar as possible to the current awicm-3-frontiers. Otherwise I would have to upload the current parallel-restart (which is more up to date with master) and we could branch this ice variables feature from there.

**Comment by JanStreffing** [comment]
Closing obsolete issue. All recently used branches of AWI-CM3.1 contain the requested feature.
