### ISSUE TITLE
Infiniband instability on Juwels

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#166]
I think this is most likely an issue for the Jülich computing center to solve, however on the off chance that someone here has already encountered this, I will also post here.

While making my TCO159L91-CORE2 AWICM3 PI control spinup on Juwels I so far encountered this error twice within 300 years of simulation. Both times the problem appeared on the FESOM2 core in the middle of decade long simulations. Both times the repeat simulation ran successfully:

```
359: <PSP:r0000359:ib:ibv_poll_cq(): Infiniband returned the wrong Opcode 5408>
359: <PSP:r0000359:connection to (10.13.6.39,20811,0x168,r0000386) (type:openib,state:open) : read : Broken pipe>
359: <PSP:r0000359:connection to (10.13.6.39,20811,0x168,r0000386) (type:openib,state:wo) : write : Broken pipe>
356: <PSP:r0000356:ib:ibv_poll_cq(): Infiniband returned the wrong Opcode 5416>
356: <PSP:r0000356:connection to (10.13.6.39,20812,0x165,r0000384) (type:openib,state:open) : read : Broken pipe>
356: <PSP:r0000356:connection to (10.13.6.39,20812,0x165,r0000384) (type:openib,state:wo) : write : Broken pipe>
357: <PSP:r0000357:ib:ibv_poll_cq(): Infiniband returned the wrong Opcode 5276>
357: <PSP:r0000357:connection to (10.13.6.39,20812,0x166,r0000384) (type:openib,state:open) : read : Broken pipe>
456: <PSP:r0000456:ib:Failed send request (status 12 : transport retry counter exceeded). Connection broken!>
```
I did not encounter this error last year when I ran 1400 years of my old AWICM3 prototype on Juwels. There are differences both on the side of FESOM2 and Juwels since then. The main difference on FESOM2 side is the async IO, while on the Juwels side I use ParastationMPI instead of IntelMPI, since only ParastationMPI proved stable at larger core numbers, as currently used e.g. by Tido for the TCO319L137-DART simulation.

You can find the simulation in question at: `/p/scratch/chhb19/jstreffi/runtime/awicm-3.1/PICT/scripts`

**Comment by koldunovn** [comment]
It really looks like a random errors in network infrastructure. Would be interesting to see what Jülich admins will answer you :)

**Comment by JanStreffing** [comment]
Closing obsolete issue. With psmpi and O2 instead of O3 this issue is not longer appearing in recent runs
