### ISSUE TITLE
Merging of parallel_restarts branch

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#189]
I had a quick chat with @koldunovn  about whether https://github.com/FESOM/fesom2/tree/parallel_restart shall be part part of the refactoring.

With AWI-CM3 we have made several hundred restarts using the new restart features at CORE2 and DART resolution. As long as you take the default fesom2 approach to what to do with the restart files (just leave them in the work folder) the parallel memory dump restarts are unbeatable in terms of speed. With the esm_tools approach of moving/copying/linking restarts files around and making a new work folder for every run, the parallel threaded netcdf restarts come out on top. We need that one at least some of the time for branching off experiments, as the memory dump locks in the number of cores used. In the future MPI/OMP hybrid parallelization might curb the number of files from the binary restarts significantly.

Nikolay also mentioned that @dsidoren has ideas to improve the concept further. Also tagging @hegish as the main developer of the idea.

**Comment by hegish** [comment]
FYI, the features of parallel restart and memory dump restart are part of the refactoring branch since end of 2021.
