### ISSUE TITLE
CMIP6: thkcello problem to regrid 

### ISSUE THREAD

**Issue by leilanepassos** [FESOM/fesom2#190]
Hei, I'm working with the AWI-CM-1-1-MR data on the DKRZ server (CMIP6: historical r1  until r3). I'm trying to regrid the variable thkcello using CDO:
cdo remapycon,global_1 thkcello_Ofx_AWI-CM-1-1-MR_historical_r1i1p1f1_gn.nc output.nc
but I'm receiving the message:
**Warning (cdf_read_ycoord): Unsupported array structure, skipped variable thkcello!
Warning (cdfInqContents): No data arrays found!
cdo    select: Open failed on >thkcello_Ofx_AWI-CM-1-1-MR_historical_r1i1p1f1_gn.nc<
               Unsupported file structure**
Questions:
**1)I've managed to regrid the variable areacello with this command. Should I use the same command with thkcello?
2)Is it the most indicated way to regrid variables: hfds (Downward Heat Flux at Sea Water Surface), wfo (Water Flux into Sea Water), tos(sea surface salinity), sos (sea surface temperature), and mlotst (Ocean Mixed Layer Thickness Defined by Sigma T)?**

**Comment by koldunovn** [comment]
Please reopen if the issue is still not addressed.
