### ISSUE TITLE
warming bias over Southern Ocean

### ISSUE THREAD

**Issue by xshi-awi** [FESOM/fesom2#201]
I am using AWIESM2.1 with zstar approach for a pre-industrial simulation, we found there is a warming bias in the Southern Ocean, which causes less sea ice production especially over Weddell Sea, this further leads to less freshwater flux during melting season and a weakening of Antarctic bottom cell. 

Here is the namelists I am using:
/pf/a/a270064/bb1029/AWIESM2.1-EXP/work_RC12_wiso

The path to the model:
/pf/a/a270064/esm_tools/awiesm-2.1-wiso

Thanks so much.

Best
Xiaoxu

**Comment by JanStreffing** [comment]
A short update on this. I had also found this in AWI-CM3 and concluded that it was a common issue between the two coupled models. Turns out that a some point during the early FESOM2 development the heat flux from enthalpy of snow falling into the open ocean was turned off. The missing heat flux from both FESOM2 based coupled models was thus approximately:

![image](https://user-images.githubusercontent.com/25483665/152759340-1942a983-8c05-4189-b7a9-9621e9295553.png)

I did the tests for AWI-CM3 and @christian-stepanek did the same for AWIESM2.1. In both cases SO warm bias is reduced by ~1°C. Here is an example plot by @tsemmler05 for the higher resolution AWI-CM3. For what I can remember it looks very similar in AWIESM2.1:

![image](https://user-images.githubusercontent.com/25483665/152759971-96f44979-eec9-4d72-8c91-160f5b1a97a7.png)

@xshi-awi Do you still se a remaining warm bias or did this solve the problem for you?
@dsidoren I solved this issue on the OpenIFS side of the coupling originally. Could you point me to where this is done in FESOM2? I'd like to make sure that we don't do this double in the future.

**Comment by dsidoren** [comment]
hi, I surprisingly found that I indeed already coupled the heat flux from enthalpy of snow in AWI-CM2 (was also made on the ECHAM side).

**Comment by JanStreffing** [comment]
I see, so the solution presented only applies to AWI-CM3.

**Comment by christian-stepanek** [comment]
@dsidoren

Dear Dmitry, thanks for the hint.

I have to admit that it is quite difficult to understand the ECHAM6 coupling equations, as names of fluxes are not really informative, and comments that explain them are sparse. Just to check that I understand the coupling correctly. Is the following correct?

```
collect.f90:
! Heat to the ocean
         ztmpw = pahflw(jl) + pahfsw(jl) + ptrflw(jl) - (pssfl(jl)+pssfc(jl))*alf
         pcplsnd(jl, 9) = pcplsnd(jl, 9) + ztmpw !*zzwat
 ! Heat to the ice
         ztmpi = pqres(jl)  + pahfice(jl)
         pcplsnd(jl,10) = pcplsnd(jl, 10) + ztmpi !*zzice
```
What I collected from various source code files:
```
! pahflw       surface latent heat flux (water)
! pahfsw       surface sensible heat flux (water)
! ptrflw       surface net longwave radiation (water)
! pssfl        surface snow flux
! pssfc        NO COMMENT ANYWHERE ON WHAT THIS IS
! alf          [J/kg]   latent heat for fusion
! pahfice(jl)  NO COMMENT ANYWHERE ON WHAT THIS IS
```
So, (pssfl(jl)+pssfc(jl))*alf computes the melt enthalpy of snow and couples this already to the atmosphere to ocean heat flux before atmosphere - ocean heat exchange is performed with FESOM2.1? We can assume that the switch __cpl_feom, activating the collection of the various heat fluxes shown in the code above, is always true if ECHAM6 and FESOM2.1 are coupled - is this correct?

**Comment by dsidoren** [comment]
Hi, looks correct. "C" stands for conductive :)

**Comment by JanStreffing** [comment]
Small update about said warming bias. Switching off MOMIX and switching on SPP, in combination with enthalpy of fusing coupling of the snow that falls into the open ocean reduced this bias from

Between AWI-CM3.0 and AWI-CM3.1 as shown here for 2m temperature of the air (tas):
<img src="https://user-images.githubusercontent.com/25483665/175484941-b0073599-2eee-465b-9e6e-e17db8b172cf.png" width=49% height=49%> <img src="https://user-images.githubusercontent.com/25483665/175484813-ff0f4ec0-1caf-4582-b0dc-549c6fe208f0.png" width=49% height=49%>

Improvement of sst is similar (3.0 vs 3.1):
<img src="https://user-images.githubusercontent.com/25483665/175485568-5478a9b1-4001-4375-b010-5f4a3a373e0d.png" width=49% height=49%> <img src="https://user-images.githubusercontent.com/25483665/175485842-c9ec5152-969d-4c7f-9ef9-efa20b838404.png" width=49% height=49%>

**Comment by xshi-awi** [comment]
?Hi Jan


Thanks so much, I will give it a try.


Best

Xiaoxu

________________________________

**Comment by chrisdane** [comment]
Nice @JanStreffing. Which part has this strong effect on mld? Switching off MOMIX or switching on SPP?

**Comment by JanStreffing** [comment]
Switching off MOMIX was somewhat stronger of those two in terms of MLD2. For sst and siconc changes it's about 50/50. It will be interesting to see if this observation holds for AWI-ESM2 as well. It did not for the higher resolution (TCO319L137-DART) experiments of @tsemmler05. He found MOMIX + SPP to work best for him.

**Comment by xshi-awi** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/73690939/175891475-a3d1e3f4-16e6-4752-887b-2f8c3d3b11f9.png">

Hi, here is a first result of the sst anomaly between SPP and the old PI reference run using momix. 
SPP has run for 193 years, and I took the last 30 years  for comparison.
both simulations are run on levante.

Best, Xiaoxu

**Comment by JanStreffing** [comment]
`SPP-MOMIX` or `MOMIX-SPP`? If this is `SPP-MOMIX` does that mean for you the warm bias gets worse? I would be interested in the MLD2 as well.

**Comment by JanStreffing** [comment]
I had neglected to mention the source code changes that activate SPP in the southern hemisphere also. We just fixed that.
@xshi-awi last 25 years of a 50 year run are probably already sufficient to get an idea of the impact.

**Comment by xshi-awi** [comment]
Thanks for the info. I will recompile the model and run it for 50 model years

**Comment by xshi-awi** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/73690939/176121669-2f67f13e-47de-48c5-978d-e1708563287b.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73690939/176121869-4aa366dd-718e-4bd6-88d6-ca334a966ce6.png">
Morning. I just finished 40-50 years, the results look like in the plots. Maybe I should use the MOMIX+SPP option?

**Comment by xshi-awi** [comment]
I made a mistake in the code and I need to re-do the simulation again. I will give some update this afternoon or tomorrow.

**Comment by xshi-awi** [comment]
Hi, 
I just performed two 60-year simulation, one of them used SPP instead of MOMIX, and the other used the combination of SPP+MOMIX, and the results in terms of the SST anomaly with regards to the standard MOMIX run is as follows:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/73690939/176383272-22359e9a-3eb5-4e33-a396-f81e398bc8b0.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/73690939/176383535-6b032ccf-5802-432a-ad8c-93bc04e2efb9.png">


It seems that the MOMIX+SPP improve the SO warming bias.

**Comment by xshi-awi** [comment]
Correct.  

We had warm bias over high latitudes and cold bias over lower latitudes, like the following plt. The good thing is the MOMIX+SPP can also improve the bias over North Atlantic.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/73690939/176391035-f675f9a9-fa0d-4022-a7b5-719f49767780.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/73690939/176391257-a9d9f2a8-9a23-4e57-a817-f8bb238504ff.png">
