### ISSUE TITLE
Async IO do not work with OpenMP at the moment

### ISSUE THREAD

**Issue by koldunovn** [FESOM/fesom2#230]
I am trying to run longer experiments with current `refactoring` branch with OpenMP on. I use 16 MPI processes and 18 OpenMP threads. In the output I see:

```
 rejecting additional async NetCDF for process:           2 use count:           2 falling back to sequential I/O on process
   0
 adding I/O stream 2D for MLD1
 rejecting additional async NetCDF for process:           4 use count:           2 falling back to sequential I/O on process
   0
 adding I/O stream 2D for MLD2
 rejecting additional async NetCDF for process:           6 use count:           2 falling back to sequential I/O on process
   0
 adding I/O stream 2D for tx_sur
 rejecting additional async NetCDF for process:           8 use count:           2 falling back to sequential I/O on process
   0
```

This is similar error message we have for test, when run on just a few cores. I guess something is wrong with determination of how many nodes the run uses. Maybe it is fine in the current stage, but might be problematic in the future :)

**Comment by hegish** [comment]
This is not an error, just an info. It occurs if there are more output streams than free FESOM processes. How many output streams are there?

**Comment by koldunovn** [comment]
Here is what I get:
```
io_listsize will be changed from          100  to           23 !
```
Ok, so as long as we have less MPI processes than output streams we are in serial I/O mode?

**Comment by koldunovn** [comment]
Here is the path to the output:
```/home/ollie/nkolduno/REFACTORING/openmp/work_long/fesom2.0.out16```

**Comment by hegish** [comment]
The jobscript is job_ollie16?

**Comment by koldunovn** [comment]
Yes.

**Comment by hegish** [comment]
Could you also run this with master branch?

**Comment by hegish** [comment]
OK, there are 16 FESOM processes, 8 Forcing input streams and 25 output streams and  in this log file. 18 Output streams are put to rank 0 for sequential output. This actually adds up as intended:

1. The first FESOM process reserved for sequential I/O (rank 0)
2. processes 2-9 read forcing in parallel
3. processes 10-16 write the first added output streams (sst, sss, ssh, uice, vice, a_ice, m_ice)
4. now all 16 processes are filled. 18 Output streams remain and these are put to sequential output on the first process (rank 0)

**Comment by koldunovn** [comment]
OK, I see. But that's mean we have to keep in mind, that there is no (or just partly) async I/O when we use small number of MPI processes. Maybe a bit more concise error message in the future, that list all used processes in nice way you presented would be nice in fome very distant future :)
