### ISSUE TITLE
Small Bug in oce_ale.F90

### ISSUE THREAD

**Issue by patrickscholz** [FESOM/fesom2#245]
https://github.com/FESOM/fesom2/blob/e6b84e21669cdc3df899a199d270f8b1493a796f/src/oce_ale.F90#L2459
cflmax on the right side is defined but has no values

**Comment by koldunovn** [comment]
Seems to be fixed? https://github.com/FESOM/fesom2/blob/500f673978c27e9cc7972692975fb01c94507d92/src/oce_ale.F90#L2491

Please reopen if not.
