### ISSUE TITLE
New restarts in refactoring not working on large meshes

### ISSUE THREAD

**Issue by koldunovn** [FESOM/fesom2#264]
Attempt to run the latest `refactoring` branch on moderate (about 3M) mesh failed at the stage of restart writing. The stdout give:

```
Do output (netCDF, restart) ...
 initializing I/O file for sst
 initializing I/O file for m_ice
 initializing I/O file for a_ice
 initializing I/O file for vice
 initializing I/O file for MLD2
 initializing I/O file for MLD1
 error in line          101 async_threads_module.F90
 error in line          101 async_threads_module.F90
  --> actualize clock file to latest restart point
 error in line          101 async_threads_module.F90
 error in line          101 async_threads_module.F90
```

Sometimes also

```
error in line          101 async_threads_module.F90
 initializing I/O file for m_snow
 error in line          611 io_meandata.F90 NetCDF: File exists && NC_NOCLOBBER
```

The `namelist.config` settings are:

```
&restart_log
restart_length=1        !only required for d,h,s cases,  y, m take 1
restart_length_unit='m' !output period: y,  d, h, s, off
raw_restart_length=1
raw_restart_length_unit='m' ! e.g. y, d, h, s, off
logfile_outfreq=720     !in logfile info. output frequency, # steps
```

The setup can be found on ollie:
`/home/ollie/nkolduno/nextgems/refactoring/work_trop`

@hegish @patrickscholz @dsidoren

**Comment by hegish** [comment]
- I could reproduce a similar error with core2
- I have fixed an issue (which I had introduced in the big merge of IO to refactoring)
- two runs with core2, 15 days, daily output and daily restart have been successful on ollie
- a job with trop mesh and the setup from above is pending in the queue

**Comment by koldunovn** [comment]
Thanks a lot, @hegish ! So this is most probably not a problem of the big mesh then. So maybe you can make a PR with a fix without waiting the trop mesh to run? :)

**Comment by hegish** [comment]
I would like to verify if the problems are really gone now. But this error has to be fixed anyway, so I did the PR already: https://github.com/FESOM/fesom2/pull/265

**Comment by hegish** [comment]
... I forgot to add a file to the last commit. Next try...

**Comment by hegish** [comment]
The run with trop mesh failed because FESOM tried to do a restart run. I do not know why yet...

**Comment by koldunovn** [comment]
You probably should change the fesom.clock.

For me the `trop_mesh` run works, I will still have to check if the restarting itself works, but restarts are created :)

Can we fix a couple of usability issues at the same time?

Currently the
`cdo sinfo /work/ollie/nkolduno/output_trop_t/fesom.2008.oce.restart/temp.nc`

give me

```
Warning (splitTimevalue): Reset wrong date/time to 0267-01-01 00:00:00!
   File format : NetCDF4 classic
    -1 : Institut Source   T Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : unknown  unknown  v instant       1   1         1   1  I32  : -1
     2 : unknown  unknown  v instant       1   1 185195448   2  F64  : -2
   Grid coordinates :
     1 : generic                  : points=1
     2 : generic                  : points=185195448 (2683992x69)
   Vertical coordinates :
     1 : surface                  : levels=1
   Time coordinate :  2 steps
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
  0267-01-01 00:00:00  0509-01-01 00:00:00
```
So the time is wrong, and the reason is, there is no attributes provided for time.

```
ncdump -h /work/ollie/nkolduno/output_trop_t/fesom.2008.oce.restart/temp.nc

netcdf temp {
dimensions:
	time = UNLIMITED ; // (2 currently)
	node = 2683992 ;
	nz_1 = 69 ;
variables:
	double time(time) ;
	int iter(time) ;
	double temp(time, nz_1, node) ;
		temp:units = "degC" ;
		temp:long_name = "potential temperature" ;
}
```

Can we add attributes to time in a form of:

```
time:long_name = "time" ;
time:units = "seconds since 2009-01-01 0:0:0" ;
```

Maybe it also make sense to:

- rename `nz_1` to `nz1` as in the output
- provide variable with depths (`nz1`), will not cost much space, but will make things easier to handle in postprocessing
- In general make naming of dimensions and variables consistent with what we have in the output (e.g. node -> nod2, description, long_name and so on). So that changing things in the restart can be done by just replacing files? The only danger I see here is that shapshots (restarts) will be easy to mix with means (most of our output).

Opinions from @dsidoren @patrickscholz ?

**Comment by hegish** [comment]
Of course we can do this.
As for the error with your trop mesh run, my run with a copy of your setup is at day 32 now and everything looks normal. It is here: /work/ollie/jhegewal/fesom2_nikolay_refactoring_branch/work-tropmesh/
I think I can stop it now, or do you want me to make really sure and finish the second month as well?

**Comment by koldunovn** [comment]
You can stop, I will play around with my version :)

**Comment by koldunovn** [comment]
@hegish The problem is back :)

I am now trying the latest version of `refactoring` branch (before I was running on your development branch), and the only thing, that is working now is `core` setup on ollie. On JUWELS even `core` did not work. Some details:

**Ollie**
_Mesh_: tropotest (1M)
_Setup_: /home/ollie/nkolduno/nextgems/ref2/work_tropotest
_Restart frequency_: 1 month
_Error_ (in output, same as before):
```
initializing I/O file for momix_length
 initializing I/O file for ty_sur
 error in line          458 io_netcdf_file_module.F90 NetCDF: Unknown file format
 error in line          458 io_netcdf_file_module.F90 NetCDF: Unknown file format
 initializing I/O file for tx_sur
 error in line          458 io_netcdf_file_module.F90 NetCDF: Unknown file format
 error in line          458 io_netcdf_file_module.F90 NetCDF: Unknown file format
 error in line          611 io_meandata.F90 NetCDF: File exists && NC_NOCLOBBER
 error in line          611 io_meandata.F90 NetCDF: File exists && NC_NOCLOBBER
```
**JUWELS**
_Mesh_: core2
_Setup_: /p/project/chhb19/hhb192/NEXTGEMS/tropotest/work_rest
_Restart frequency_: 1 year
_Error_ (in STDOUT):
```
<PSP:r0000005:precon(0x33fbf60): write(28, 0x36bea30, 8) : Broken pipe>
forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE
Image              PC                Routine            Line        Source
fesom.x            00000000006D2CCF  for_execute_comma     Unknown  Unknown
fesom.x            000000000058D4E5  Unknown               Unknown  Unknown
fesom.x            000000000058B749  Unknown               Unknown  Unknown
fesom.x            0000000000478B02  Unknown               Unknown  Unknown
fesom.x            00000000006727D7  Unknown               Unknown  Unknown
fesom.x            00000000004171E2  Unknown               Unknown  Unknown
libc-2.28.so       0000153FCB556493  __libc_start_main     Unknown  Unknown
fesom.x            00000000004170EE  Unknown               Unknown  Unknown
<PSP:r0000015:connection to (10.13.5.19,0,(nil),r0000241) (type:demand,state:closed) : connect : Connection refused>
Fatal error in PMPI_Send: Other MPI error, error stack:
PMPI_Send(159).....: MPI_Send(buf=0x151d5c8a2080, count=440, MPI_DOUBLE_PRECISION, dest=241, tag=42, comm=0x84000002) failed
mpid_isend_done(40): write to socket failed - request state:send(pde)done<PSP:r0000139:connection to (10.13.5.19,0,(nil),r0000241) (type:d
emand,state:closed) : connect : Connection refused>
Fatal error in PMPI_Send: Other MPI error, error stack:
PMPI_Send(159).....: MPI_Send(buf=0x145d222fa080, count=440, MPI_DOUBLE_PRECISION, dest=241, tag=42, comm=0x84000002) failed
mpid_isend_done(40): write to socket failed - request state:send(pde)doneFatal error in PMPI_Send: Other MPI error, error stack:
```

_Mesh_: tropotest
_Setup_: /p/project/chhb19/hhb192/NEXTGEMS/tropotest/work_tropotest
_Restart frequency_: 1 month
_Error_ (in STDOUT): Same as for core

**Comment by hegish** [comment]
We had the EXECUTE_COMMAND_LINE problem also with the awicm3 fesom on juwels. It might have something to do with memory consumption, which causes the EXECUTE_COMMAND_LINE. Can you reproduce the problem?

**Comment by koldunovn** [comment]
The problem happens every run, so yes.

**Comment by hegish** [comment]
which runscript ca I use to reproduce it,  job_juwels or job_juwels_new?

**Comment by koldunovn** [comment]
It's `job_juwels`.

**Comment by hegish** [comment]
I can not reproduce the problem on ollie

**Comment by koldunovn** [comment]
Which mesh did you try on ollie?

**Comment by hegish** [comment]
/work/ollie/nkolduno/meshes/trop/ with np2304

**Comment by koldunovn** [comment]
This is wrong mesh. I tried with /work/ollie/nkolduno/meshes/tropotest/ on 1728 cores

**Comment by koldunovn** [comment]
It works for Dima on ollie. So probably the Juwels is a real problem. Will try to do very clean run again.

**Comment by koldunovn** [comment]
The `trepotest` on ollie works also for me - not sure what was the problem. 

The problem on `juwels` persists.

**Comment by hegish** [comment]
Yes, this is a weird problem. It may be related to the way how Fortran's EXECUTE_COMMAND_LINE (it forks a subprocess). I can also reproduce it (currently) on juwels with a small awicm3 setup. I am using mkdir from C now, hopefully it will help.

**Comment by hegish** [comment]
> The problem on `juwels` persists.

I think I cold fix the EXECUTE_COMMAND_LINE problem on juwels.
However, errors like
 <PSP:r0000005:precon(0x33fbf60): write(28, 0x36bea30, 8) : Broken pipe>

is still there with awicm3. They are issued from both Fesom and OIFS. I suspect it has something to do with the file count limitation per project.
Could you please check to which project dir you are writing the output to? And also check the file count limit graph in judoor.

**Comment by koldunovn** [comment]
Great! I have this warnings for other simulations, they does not seem to affect the run. We are below quota for file number and storage in all projects.

**Comment by hegish** [comment]
see here: https://github.com/FESOM/fesom2/pull/272

**Comment by koldunovn** [comment]
The new version works on juwels. Thanks a lot @hegish !
