### ISSUE TITLE
PGI compile error

### ISSUE THREAD

**Issue by goord** [FESOM/fesom2#3]
The compilation of fesom-2 rev. 8c6bf9b04ec109c229b7535e821352e937078d9c with PGF90 aborts with the error
```
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 68)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 69)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 70)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 71)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 72)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 73)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 75)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 76)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 79)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 85)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 86)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 93)
PGF90-S-0155-Illegal POINTER assignment - pointer target must be simply contiguous (/home/gijstest/FESOM2-CORE2/fesom2/src/associate_mesh.h: 94)
```

**Comment by rakowsk** [comment]
The arrays are contiguous, which we now as programmers, but the compiler must assume they are not to be on the safe side. With the Intel and Gnu compiler, it worked to convince the compiler to have contiguous access with known first dimension with e.g.:
gradient_vec(1:6,1:myDim_elem2D) => mesh%gradient_vec

If the dimensions are skipped, it should work also for PGI compilers, at the price of a performance loss, because in loops with gradient_vec, the memory layout is not known at compile time.

Background:
mesh%gradient_vec is defined as allocatable, dimension(:,:)
We know that it is always
allocate(mesh%gradient_vec(6,1:myDim_elem2D))
but the compiler assumes it could also be anything else, say 
allocate(mesh%gradient_vec(8,1:myDim_elem2D))
and in this case, gradient_vec(1:6,1:myDim_elem2D) is not contiguous.

As far as I remember, the performance gain for Intel compiled code was about 10% with the dimensions given. Is there any flag or preprocessor directive for PGI to make it know the actual array dimensions?

**Comment by goord** [comment]
We may declare the mesh allocatable arrays to be contiguous memory with the ```contiguous``` keyword. I guess the compiler should be able to deduce those pointers to be contiguous too?

**Comment by rakowsk** [comment]
Hopefully. However, the problem remains that the first dimension in the allocatable statement somewhere else in the code and the pointer are allowed to differ, thus: if we allocate gradient_vec(8,:), it is contiguous for the first dimension 8, and gradient_vec(1:6,:) still  would be a non-contiguous sub array.
It only works because we know that we allocate gradient_vec(6,:).

I might really miss an important bit! Even before FESOM2 was refactored, it was a performance issue that the global fields are regarded by the compiler as "How should I know how this field gets allocated? There might be gaps, lets compile general code here". Local fields, with the dimension set in the same subroutine, yield faster code. There must be a way to tell a compiler in a more general way that we know how the (:,:) dimension is chosen...

**Comment by goord** [comment]
This is exactly what the contiguous keyword is there for: it tells the compiler that the pointer (or assumed-shape array) is guaranteed --although not obvious--  to be contiguous and allows vectorization.

I will experiment a bit with this.

**Comment by goord** [comment]
@rakowsk can you explain to me the purpose of associate_mesh.h? Is it just to create pointers to mesh arrays to avoid changing the code too much, or are you also creating (contiguous) array slices?

**Comment by rakowsk** [comment]
Exactly. 
1. associate_mesh.h was introduced with the t_mesh type to avoid changing the code too much (and keep it readable)
2. With the pointers, the code first got slower, compared to global arrays and no t_mesh type. We realized that by additionally stating the array bounds, we could finally tell the compiler that all loops are working on contiguous array slices.

**Comment by rakowsk** [comment]
Summing up, your first aim is probably to get working with the PGI compiler and focus on other issues. For this, it is fine to just skip the array bounds.
But we have to keep it in mind, find a better solution or (ugly) use preprocessor directives. It's just that I do not like the idea that we loose, say, 10% performance on CPUs to make the code work on GPUs at all ;-)

**Comment by goord** [comment]
Hi @rakowsk I have observed the performance degradation too, it's even larger than 10% so I'm looking for a way to avoid that whilst keeping the PGI compiler happy

**Comment by goord** [comment]
Hi @rakowsk I have noticed that keeping only the lower bound in the pointer assignments makes the code compile with pgfortran and does not cause a performance degradation with ifort. I do not know why the performance is worse if we omit the indexing on the pointer whatsoever, I would assume in both cases the array descriptor is copied form the target array to the pointer. Comparing compiler reports indicates more temporary copies are made when the bounds are omitted, resulting in slower code.

Perhaps you can run a test with this branch to confirm my observations?

**Comment by rakowsk** [comment]
That's interesting! I have no idea why a simple (1:,1:) helps the compiler as much as a full, say, (1:6,1:). Hmm, we do not have field sizes that fit into a cache line, maybe, now the trailing part of a vectorized loop can be optimized, and the remainder cannot in our case?! 
Ok, stop guessing, I'll give it a try!

**Comment by rakowsk** [comment]
* Core2 setup (126,000 nodes) on 36 cores (2x Intel Broadwell, 1 node of ollie.awi.de);
* 450 time steps; 
* Compiled with 
   ** ifort 19.0.7, options -O3 -r8 -fp-model precise -xHost -ip 
   ** gfortran 8.2.0, options -ffast-math -march=native -funroll-loops -ffree-line-length-none
    (Remark: I was to lazy to check for the options corresponding to -r8 and -fp-model precise, which probably makes the gnu code a bit faster, see below. But we should get rid of -r8 anyhow, and AFAIR, gfortran does not even compile with 8 byte real, because we explicitly use 4byte real for the IO, and gfortran is more picky here.) 
* Intel MPI 19.1.1
* associate_mesh.h with both bounds, lower bound, no bounds
* timings according to fesom log "runtime total (ice+oce)"
* Two runs for each setup, lower value is chosen.
          
                           ifort          gfortran
no bounds           220.1s     213.0s
lower bounds      217.4s     212.3s
both bounds        215.7s     207.4s (PGI would complain)

With more cores and multiple compute nodes, the result gets less clear. MPI effects take over.  
And this is probably already a memory bandwidth bound regime, which makes single core optimizations less visible.  I'll setup a partition with even less subdomains and run the comparison again.

**Comment by rakowsk** [comment]
Here the timings for the same experiment with 18 MPI tasks, bound to each second core on 2x 18 core Broadwell:
     
compiler         ifort      gfortran
no bounds      307.5s   290.8s
lower bounds  301.6s  288.7s
both bounds    299.5s  278.9s (PGI would complain)

In the setups I used, I don't see a difference of 10%, but it is significant.
The effect of "only lower bounds" compared to "no bounds" is stronger for Intel than for Gnu, and vice versa for "only lower bounds" to "both bounds".

**Comment by goord** [comment]
We can define a preprocessor variable to use only lower bounds in the pgi case. It does not make for beautiful code, but it saves you from performance loss

**Comment by rakowsk** [comment]
Sounds like the most pragmatic solution at the time being! Just go ahead.

We'll keep it in mind and maybe, we can improve this issue later.

**Comment by rakowsk** [comment]
Another observation, with gfortran 8.2.0 and -fcheck all: fesom.x stops with

> Error termination. Backtrace:
> At line 69 of file associate_mesh.h
> Fortran runtime error: Target of rank remapping is too small (1 < 2262)

This is geo_coord_nod2D, and at the point of failure, the array is not allocated...
It helps to insert
> if (allocated(mesh%geo_coord_nod2D)) &
>                  geo_coord_nod2D(1:2,1:myDim_nod2D+eDim_nod2D) => mesh%geo_coord_nod2D

of course, for all fields in associate_mesh.F90. The Intel ifort 19.1.1 did not complain here.
I'll check this into my branch at gitlab.dkrz.de

**Comment by donners-atos** [comment]
Hello @goord,

I posted the first error message on the Nvidia forum:

https://forums.developer.nvidia.com/t/attempt-to-use-a-subroutine-as-a-function/153981

**Comment by goord** [comment]
Hi @donners-atos thanks for that, I made a workaround by moving the target subroutine to the module that contains the pointer.

Also I noticed PGI doesn't seem to apply the 'nopass' qualifier to all comma-separated procedure declarations...

**Comment by goord** [comment]
I was able to compile with these fixes, but now I am fighting linker errors that emerge from this asynchronous forcing reader business...

**Comment by donners-atos** [comment]
Hello @rakowsk, have you considered the ASSOCIATE statement?

**Comment by donners-atos** [comment]
ok, I see that the ASSOCIATE construct was used until end of last year. What was the reason to change to pointers instead?

**Comment by goord** [comment]
I think this was introduced to facilitate the modularization of the code into 'dwarfs'

**Comment by rakowsk** [comment]
We tested different ways for associate_mesh.h, when we started to get rid of the global variables. With the current pointers, which tell the compiler the size of the arrays, we get the fastest code. Only PGI refuses this information...
Associate was out first try, most straight forward, however, it resulted in slower code. I do not remember the details, but originally, all attempts resulted in considerable slower code than the version with global arrays. The pointers w/o array dimensions were faster than associate, and adding the array dimensions improved the performance even compared to global arrays. All tests were performed with Intel Compiler.

**Comment by rakowsk** [comment]
Hi again,
dug in mails and found output of -qopt-report=5 for one file, ice_EVP.optrpt, subroutine stress_tensor. Obviously, associate introduced an overhead, at least with Intel ifort, probably version 19 or maybe 18, with the obvious difference being temporaries.

1. with #include "associate_mesh.h" with associate for all fields:

    Routine temporaries
        Total         :     463
            Global    :      87
            Local     :     376
        Regenerable   :       5
        Spilled       :      57

2. Limited to the fields used in the specific routineassociate(metric_factor=>mesh%metric_factor, &
elem2D_nodes=>mesh%elem2D_nodes, &
gradient_sca=>mesh%gradient_sca)

    Routine temporaries
        Total         :     206
            Global    :      53
            Local     :     153
        Regenerable   :       4
        Spilled       :      26


3. No associate, no pointers, mesh% in the code:

    Routine temporaries
        Total         :     153
            Global    :      36
            Local     :     117
        Regenerable   :       5
        Spilled       :      11

4. Pointers for the specific fields (not yet with array bounds):
   Routine temporaries
        Total         :     177
            Global    :      42
            Local     :     135
        Regenerable   :       4
        Spilled       :      11

**Comment by donners-atos** [comment]
Concerning https://forums.developer.nvidia.com/t/attempt-to-use-a-subroutine-as-a-function/153981:

NVidia confirmed it as a compiler bug: TPR #29015.

**Comment by JanStreffing** [comment]
Closed for inactivity.
