### ISSUE TITLE
Compile Problems on Mistral

### ISSUE THREAD

**Issue by pgierz** [FESOM/fesom2#30]
Hi all,

I wanted to test out the master branch with ECHAM-6.3.05p2 Concurrent Radiation to see about starting our AWI-ESM 2.1 PI tests. Unfortunately, I ran into problems when trying to compile on DKRZ:

```
/mnt/lustre02/work/ba1066/a270077/fesom-freezing-tests/model_codes/awiesm-2.1/fesom-2.0/src/cpl_driver.F90(164): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MOD_OASIS_AUXILIARY_ROUTINES]
    use mod_oasis_auxiliary_routines, ONLY:	oasis_get_debug, oasis_set_debug
--------^
/mnt/lustre02/work/ba1066/a270077/fesom-freezing-tests/model_codes/awiesm-2.1/fesom-2.0/src/cpl_driver.F90(164): error #6580: Name in only-list does not exist or is not accessible.   [OASIS_GET_DEBUG]
    use mod_oasis_auxiliary_routines, ONLY:	oasis_get_debug, oasis_set_debug
------------------------------------------------^
/mnt/lustre02/work/ba1066/a270077/fesom-freezing-tests/model_codes/awiesm-2.1/fesom-2.0/src/cpl_driver.F90(164): error #6580: Name in only-list does not exist or is not accessible.   [OASIS_SET_DEBUG]
    use mod_oasis_auxiliary_routines, ONLY:	oasis_get_debug, oasis_set_debug
-----------------------------------------------------------------^
compilation aborted for /mnt/lustre02/work/ba1066/a270077/fesom-freezing-tests/model_codes/awiesm-2.1/fesom-2.0/src/cpl_driver.F90 (code 1)
make[2]: *** [src/CMakeFiles/fesom.dir/cpl_driver.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/fesom.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/pf/a/a270077/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270077/.local/lib/python3.7/site-packages/esm_master/cli.py", line 74, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270077/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 50, in main_flow
    user_task.execute() #env)
  File "/pf/a/a270077/.local/lib/python3.7/site-packages/esm_master/task.py", line 430, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/sw/spack-rhel6/anaconda3-2020.02-dqbodz/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-fesom-2.0-paleodyn_script.sh']' returned non-zero exit status 2.
```

[To reproduce](https://gitlab.awi.de/paleodyn/Projects/PalMod/fesom-freezing-tests) (The link may be give you a 500 error, it is AWI internal only):
```
$ esm_master get-awiesm-2.1
$ cd awiesm-2.1/fesom-2.0
$ git checkout .  # remove changes made by esm-master to CMakeLists.txt
$ git remote set-url origin git@github.com:FESOM/fesom2.git
$ git fetch
$ git checkout master
$ git pull # probably not needed
$ cd ../../
$ esm_master comp-awiesm-2.1
```

Any hints @koldunovn? I know coupling isn't really your area of expertise. @JanStreffing I remember reading an issue a while ago that you also had compile issues, might this be related?

**Comment by pgierz** [comment]
OK, I have found the problem. It turns out, that @JanStreffing compiles his AWICM-3 model consisting of OIFS/FESOM2 (the master branch) and couples using oasis3-mct version 4. We had coupled ECHAM6/FESOM2 (@dsidoren's 2019 version) with oasis3-mct version 2. The names of some of the library functions have slightly changed.

So, question from my side: would it be feasible to do one of the following, and if yes, which:
1. Add options in FESOM2 to use the old coupler version (this apparently worked in Sidorenko 2019, so it should work now again)
2. Add options in ECHAM6 to include the new version of the coupler. I would need to figure out which names changes. I'm trying to get my head around it, but maybe someone else is faster.

Any thoughts, ideas?

Also as info for: @christian-stepanek

**Comment by JanStreffing** [comment]
So I guess this is the code section of relevance:

https://github.com/FESOM/fesom2/blob/766daef097c085db438235f800cb2e6edd83f6a7/src/cpl_driver.F90#L163-L167

I use different names for oasis3 routines depending on the coupling. But really it's not the coupling but rather the oasis version that is different here. If you want to be able to use mct4 with awicm2 you can probably use what awicm3 selects here and get rid of this ifdef. Perhaps for the old oasis3mc2 we can have a new directive called  `__mct2`.

**Comment by pgierz** [comment]
@JanStreffing: no, my merge messed up and on Ollie I compiled without the coupling directives turned on...

**Comment by JanStreffing** [comment]
Makes sense

**Comment by pgierz** [comment]
So, interestingly enough, these lines:
https://github.com/FESOM/fesom2/blob/766daef097c085db438235f800cb2e6edd83f6a7/src/cpl_driver.F90#L163-L167
are still the same and haven't changed...

Interestingly enough, something in ESM tools induces the mistake. Even though I explicitly try to compile AWIESM2, I have in my CMakeLists.txt of FESOM:
```
cmake_minimum_required(VERSION 3.4)

# set default build type cache entry (do so before project(...) is called, which would create this cache entry on its own)
if(NOT CMAKE_BUILD_TYPE)
	message(STATUS "setting default build type: Release")
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build, options are: None(CMAKE_CXX_FLAGS or CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.")
endif()

project(FESOM2.0)
set(TOPLEVEL_DIR ${CMAKE_CURRENT_LIST_DIR})
set(FESOM_COUPLED ON CACHE BOOL "compile fesom standalone or with oasis support (i.e. coupled)")
set(OIFS_COUPLED ON CACHE BOOL "compile fesom coupled to OpenIFS. Also needs FESOM_COUPLED to work)")
set(CRAY OFF CACHE BOOL "compile with cray ftn")
#set(VERBOSE OFF CACHE BOOL "toggle debug output")
#add_subdirectory(oasis3-mct/lib/psmile)
add_subdirectory(src)
```

Specifically, I think the `OIFS_COUPLED ON` might be the culprit ;-) I'm still trying to find out what exactly in esm_master makes that happen, since the sed replacement command is very specific for FESOM_COUPLED....

```
sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
```

**Comment by pgierz** [comment]
OK, the problem is that @JanStreffing very lovely comment also contains the string `FESOM_COUPLED`, and sed is doing exactly what we tell him to do. 🤦  I will change the sed to look for `set(FESOM_COUPLED` instead of just `FESOM_COUPLED`. That should solve it.

```
set(OIFS_COUPLED ON CACHE BOOL "compile fesom coupled to OpenIFS. Also needs FESOM_COUPLED to work)")
```
