### ISSUE TITLE
Fesom2 outputting 2-hourly files when requested 1-hourly output frequency

### ISSUE THREAD

**Issue by mathanase** [FESOM/fesom2#308]
For a set of experiments with AWICM3 on Juwels, I would need hourly fesom2 output for a selected set of variables. 

I modified the `namelist.io` file as usual e.g.:

> 'a_ice     ',1, 'h', 4,
> 'm_ice     ',1, 'h', 4,

I thought the first string was the output frequency, the second string was the unit, and the last string was the precision.

However, the resulting output is 2-hourly instead of 1-hourly. 
Does anyone have any idea what could be the issue here? Many thanks in advance.

**Example experiment:**
`/p/scratch/chhb19/athanase1/06_WORK/awicm3-v3.0/HIST_runs/HIST_nudged_MOSAIC_April2020_HF/HIST_nudged_MINU_02_HF/`

**Fesom2 namelist:**
`/p/scratch/chhb19/athanase1/06_WORK/awicm3-v3.0/HIST_runs/HIST_nudged_MOSAIC_April2020_HF/HIST_nudged_MINU_02_HF/config/fesom/namelist.io`

**Fesom2 output e.g.:**
`/p/scratch/chhb19/athanase1/06_WORK/awicm3-v3.0/HIST_runs/HIST_nudged_MOSAIC_April2020_HF/HIST_nudged_MINU_02_HF/outdata/fesom/a_ice.fesom.2020.nc`

**Comment by mathanase** [comment]
Maybe @mandresm @JanStreffing or @koldunovn have some insights?

**Comment by hegish** [comment]
Are you sure the FESOM timestep is a multiple of an hour?

**Comment by koldunovn** [comment]
I didn't know the 'h' was even available, or learn some time ago it's broken. Currently solution is to use steps ("s"), that is equivalent to 1 hour. Also @hegish might be right in spotting the reason :) 

Related to:
https://github.com/FESOM/fesom2/issues/191

**Comment by mathanase** [comment]
I was not aware that the output frequency 'h' was outdated/broken. I must have looked at some old documentation!

Indeed, when I request the output frequency unit 's', I get the requested output (i.e. every n time step of 40 minutes).
Thanks!
