### ISSUE TITLE
Closed seas e.g. Caspian

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#310]
I wrote for the introduction of FESOM2 in the AWI-CM3 paper:

> As a limitation based on technical design FESOM2 requires the worlds oceans to be described as one continuous basin. Therefore, bodies of water that are cut off by land from the worlds oceans, such as the Caspian Sea and the Great Lakes can not be simulated via FESOM2, and have to be included as lakes via the OpenIFS lake module. For the low resolution CORE2 mesh in particular, additional ocean basins with narrow outflow channels are not included. These are, the White Sea, Persian Gulf, Black Sea, and the Gulf of Ob. 

Qiang commented that he thinks this is not actually a technical limitation but rather a design choice. 

Can any of you clarify? Do we in principle have the option to simulate e.g. the Caspian Sea in a global FESOM2?

**Comment by koldunovn** [comment]
Well, technically Caspian Sea and the Great Lakes are lakes. It might cause problems on the very high resolutions, though, when circulation there become important. But I would agree with Qiang, it's a design choice. I don't thing there is an easy way to include Caspian Sea.

**Comment by JanStreffing** [comment]
Thank you!
