### ISSUE TITLE
Writing restarts after 50 years produces only raw, not netcdf files

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#322]
I'm faced with the following issue:
I ran simulations of length 50 years (1.1.2000 - 31.12.2049) with AWI-CM3. When I run 10 year long chunks everything is fine. When I run one 50 year long simulation, the model runs until the end, and then hangs when it should write restarts.

I checked, and found that:
OpenIFS has written restarts and shut down
FESOM2 has written year end output files, as well as raw restarts, **but no netcdf restarts**

It appears as though there is some calendar issue by which the model does not write raw and netcdf restarts at the same timestep in this configuration. 

folder containing the failed restart:
`/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/PRHEAT/run_20000101-20491231/work`
fesom2 branch: awicm-3-frontiers_parallel-restart (6bb94dfd3017b5bb796d60d144f0f204f2681e94)

As this is a coupled run, the model then waits for OASIS coupling and hangs in MPI_WAITALL until timeout. The discrepancy might not be obvious in standalone FESOM2 runs, as FESOM2 can just run whatever additional timesteps it needs until netcdf restart files are written.

**Comment by hegish** [comment]
Thank you for the report. I can not access the directory from above:
ls: cannot access '/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/PRHEAT/run_20000101-20491231/work': No such file or directory

**Comment by JanStreffing** [comment]
Hey Jan, I think just shut down juwels for maintenance: https://status.jsc.fz-juelich.de/

**Comment by JanStreffing** [comment]
Actually, I can still access it. You are a member of chhb19, right?

**Comment by hegish** [comment]
I am sorry, I tried it on aleph (:

**Comment by hegish** [comment]
hm, in there is no frequency set for the memory dump in `namelist.config`. Netcdf restart is set to 50 y. The default frequency for the memory dump is monthly I think. So that might be the difference. I will try to reproduce it. Please keep the `/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/PRHEAT/run_20000101-20491231/work` dir for a while.

**Comment by JanStreffing** [comment]
Will do! The job is still in the queue and hanging for another 5 hours. After that some more output from the crash will be written. Or would you like me the cancel the slurm job now?
It does spend some resources just sitting there..

**Comment by hegish** [comment]
I will copy some files, you can just continue

**Comment by hegish** [comment]
I can not reproduce the problem with a minimal setup and 50 years.
However, I noticed FESOM does not use the restart frequency from `namelist.config` as expected. You have
```
    restart_length = 50
    restart_length_unit = 'y'
```

But if `y` is specified, the digit is not taken into account and a yearly restart frequency is being used.
So for your above setup there should be a restart directory for each of the 50 years. But only the last one is missing, 2049.
For the yearly output, the 2049 is also missing (e.g. 'N2'). The monthly output for year 2049 exists, but the last month is missing.

**Comment by JanStreffing** [comment]
Thanks for investigating. I take away that this is likely caused by a mismatch of OpenIFS and FESOM2 run length then. @mandresm and I will look into that and report back.

**Comment by hegish** [comment]
I also did a test with FESOM standalone starting from year 2000 and 2049 is the last yearly restart for a 50 y run.

**Comment by mandresm** [comment]
@hegish , can you share the path to that simulation?

**Comment by hegish** [comment]
No sorry, I did that on my Laptop.

**Comment by JanStreffing** [comment]
No longer happening, closing old issue
