### ISSUE TITLE
Remapping 3D FESOM2 data with cdo

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#323]
Most researchers outside of AWI will interact with FESOM2 output after remapping to regular grid, e.g. via cdo.

For AWI-ESM-1-1-MR CMIP6 data this works fine. Here is the salinity vertically interpolated at 1000m depth and remapped to a 2° regular grid via:
```
cdo genycon,r180x91 -selname,salt -setgrid,/pool/data/AWICM/FESOM1/MESHES/core/griddes.nc weights_unstr_2_r180x91_so.nc
cdo -remap,r180x91,weights_unstr_2_r180x91_so.nc $in $out
```
![image](https://user-images.githubusercontent.com/25483665/158974362-15b5b5d0-7b8c-4343-9223-7dede8a5ea93.png)

I do the same for FESOM2 output, and the missval being 0 messed things up:
```
cdo genycon,r180x91 -selname,salt -setgrid,/work/ab0246/a270092/input/fesom2/core2/core2_griddes_nodes.nc
cdo -remap,r180x91,weights_unstr_2_r180x91_so.nc $in $out
```
![image](https://user-images.githubusercontent.com/25483665/158970718-31d1d0fc-3e65-41b2-ae01-05e79a3a75f3.png)

I tired the obvious `-setctomiss,0` and it mostly works. But it turns out, not all of the spurious values are exactly 0:
```
cdo genycon,r180x91 -selname,salt -setgrid,/work/ab0246/a270092/input/fesom2/core2/core2_griddes_nodes.nc
cdo  -remap,r180x91,weights_unstr_2_r180x91_so.nc -setctomiss,0 $in $out
```
![image](https://user-images.githubusercontent.com/25483665/158974234-c936d29d-5435-47d7-a73b-fd4572729b34.png)

For some points along the coasts there is still a spuriously low salt concentration. Any advice how to remap FESOM2 output better?

**Comment by koldunovn** [comment]
Can you try to set missing points before doing interpolation?

**Comment by JanStreffing** [comment]
I had the same idea, unfortunately, no difference.

**Comment by koldunovn** [comment]
Can you list the commands you use for first setting the missing values and then interpolate?

**Comment by JanStreffing** [comment]
```
for var in salt;
do
        cdo -setctomiss,0 ${outdir}/${var}_${tmpstr}.nc ${outdir}/${var}_${tmpstr}_nan.nc
        cdo genycon,r180x91 -selname,${var} -setgrid,$gridfile  ${outdir}/${var}_${tmpstr}_nan.nc ${outdir}/weights_unstr_2_r180x91_${var}.nc &
done
wait


for var in salt;
do
        cdo -L -splitlevel -remap,r180x91,weights_unstr_2_r180x91_${var}.nc -selname,${var} -setgrid,$gridfile ${var}_${tmpstr}_nan.nc ${var}_${tmpstr}_ &
done
wait


for var in salt;
do
        for lvl in "000010" "000100" "001000" "004000";
        do
                mv ${var}_${tmpstr}_${lvl}.nc ${var}_${tmpstr}_${lvl}_remap.nc &
        done
done
wait


for lvl in "000010" "000100" "001000" "004000";
do
        cdo chname,salt,so salt_${tmpstr}_${lvl}_remap.nc so_${tmpstr}_${lvl}.nc &
done
wait


for var in so
do
        for lvl in 10 100 1000 4000;
        do
                #cdo -L splitseas -setctomiss,0 -expr,so=(so<20.0)?0.0:so;  -yseasmean ${var}_${tmpstr}_$(printf "%06d" $lvl).nc $outdir/${var}_${model_name}_198912-201411_${lvl}m_ &
                cdo -L -splitseas -yseasmean ${var}_${tmpstr}_$(printf "%06d" $lvl).nc $outdir/${var}_${model_name}_198912-201411_${lvl}m_ &
        done
done
wait

```

**Comment by koldunovn** [comment]
Looks OK to me. One thing that might happen is that interpolation in cdo ignores the missing flag, and continue to use zeros.  So you can try to replace missing values by `nan` with something like `setmissval,nan`.

**Comment by chrisdane** [comment]
Jan, can you provide the ok and not-ok versions with the same colorbars? Its difficult to see the actual problem.

**Comment by JanStreffing** [comment]
@koldunovn `setmissval,nan` seems to have no effect. I tried it before and after `-setctomiss,0`. I think this is expected, as the command only changes a missval that cdo already recognizes as such to a different value. Is is possible that the low but non zero values stem from using partial cells? As in total salt content of a partial cell being divided by the whole cell area?

@chrisdane The first plot from FESOM1 is ok, the last one from FESOM2 is not. They are on the same colorbar. I've outlined areas where the problem appears and uploaded the last plot with much dpi (click for larger version). 
![AWI-CM3-REF2](https://user-images.githubusercontent.com/25483665/159001809-fe2851cb-90f5-4c82-b04d-ef00271a1089.png)

Compared to:
![AWI-ESM-1-1-LR](https://user-images.githubusercontent.com/25483665/159005316-b650f20e-0616-474a-8bc5-a38b1090e6cf.png)

**Comment by chrisdane** [comment]
How does the data look like without interpolating? Maybe what you call not ok is just the model result? :D

**Comment by JanStreffing** [comment]
Luckily that's not the case. Here is the same plot with pyfesom2:
![AWI-CM3-pyfesom](https://user-images.githubusercontent.com/25483665/159136739-0d4006ec-443f-4b9a-b076-0421c4c65508.png)

**Comment by pgierz** [comment]
One spontaneous idea: it looks as if @JanStreffing is using something that (in the background maybe?) uses `contourf`. This does some form of, for lack of a better word, "smearing" or interpolation to make "nice" (or "un-nice") contours. It would be interesting to see what happens instead if you directly plot the values without interpolation, e.g. with something like `pcolormesh`. It could be, that it is mixing an extreme negative value (probably a default for land points) with the real value in the ocean, thus producing these brown patches.

**Comment by pgierz** [comment]
Is that an LGM mesh?

**Comment by helgegoessling** [comment]
No, but at 1000m depth!

**Comment by JanStreffing** [comment]
no, it's present day, but 1000m depth

**Comment by pgierz** [comment]
You do a remap with `cdo genycon,r180x91`. Does the same problem occur with other remapping methods? (Funnily enough, there is a remapping discussion also occurring in another group)

**Comment by helgegoessling** [comment]
@pgierz , my plots above suggest it's in the data after all, so not a remapping issue.

**Comment by pgierz** [comment]
...I need a whiteboard for this, but: what happens in partial polyhedrons? However, I would expect that sort of problem to then occur at any coastline, not just Greenland and New Zealand??

![IMG_1326](https://user-images.githubusercontent.com/2444231/159514067-7c22d903-6633-4481-903a-e4a1b71ff91e.jpeg)

**Comment by chrisdane** [comment]
It does @pgierz: Zoom in this figure you see very low salinity values (blueish) along all coastlines:
![awi-cm3_so_global_Jan_2049_const](https://user-images.githubusercontent.com/26486859/159523238-d353d5c6-8a6d-4baf-9330-99577c9b524a.png)
Maybe its the `intlevel,1000`? Where is the raw model output salt.fesom.2049.nc @JanStreffing?

**Comment by JanStreffing** [comment]
Maybe.. though it would have to behave differently for FESOM2 with intlevel than for FESOM1. 
The file is here:` /mnt/lustre01/work/ab0246/a270092/download/salt.fesom.2049.nc`

**Comment by JanStreffing** [comment]
ooooh, yes of course it behaves differently for intlevel. Because the values that are in the ground on the lower level are 0 instead of nan.

**Comment by JanStreffing** [comment]
Indeed, simply placing `-setctomiss,0` before the vertical interpolation fixed the issue. Thank you all!
![image](https://user-images.githubusercontent.com/25483665/159563582-38974b12-6706-4054-bdc6-559aa169356c.png)

**Comment by pgierz** [comment]
So it is written down in case some one goes down this particular rabbit hole again: what was the final CDO command?

**Comment by helgegoessling** [comment]
Oh gosh, I assumed the "native output" was native output ;-) ... should have looked into the cdo history :confounded:

**Comment by helgegoessling** [comment]
> So it is written down in case some one goes down this particular rabbit hole again: what was the final CDO command?

If you look at a level that is a model (output) level, then everything's fine. If however you need to look at an intermediate level for which vertical interpolation is required, it would be (example, all in one command):
`cdo remapcon,r180x91 -intlevel,${level} -setctomiss,0 -setgrid,${gridfile} ${ifile} ${ofile}`
... with the order of setctomiss and intlevel being critical.

**Comment by chrisdane** [comment]
@JanStreffing: the last figure you showed might also be not fully correct? The land sea mask does not fit to 1000m depth. See e.g. Panama Strait? Is this due to ncview?

@helgegoessling: but this command sets potentially correct values, e.g. temperature = 0°C, to nan, right? Wouldn't this be wrong as already asked by @JanStreffing in #289?

**Comment by helgegoessling** [comment]
> but this command sets potentially correct values, e.g. temperature = 0°C, to nan, right? Wouldn't this be wrong as already asked by @JanStreffing in https://github.com/FESOM/fesom2/issues/289?

Yes. That's why it would be better to put NANs into the FESOM output in the first place. But also it's extremely unlikely to get exact zeros for actual temperatures, so for the time being I guess we can live with it.

**Comment by pgierz** [comment]
The messed up Panama is likely due to the coarse interpolation of 2˚x2˚, there were similar interpolation "hiccups" back in the MPIOM days. (oh man, I am starting to sound like a grandpa)

**Comment by koldunovn** [comment]
@chrisdane  FESOM did not have exact 0 in 20 years. There is a small chance there will be one in the next 20 :)

**Comment by helgegoessling** [comment]
> > That's why it would be better to put NANs into the FESOM output in the first place.
> 
> yes, but unfortunately NaN is treated differently in different post-processing languages. My recommendation would therefore be to tell FESOM to write a very large negative number (e.g. `-9e99`) and then leverage the `_FillValue` attribute of NetCDF.

Well, that's quasi what I meant :-).
