### ISSUE TITLE
ssh drop in refactoring branch coupled simulations with zstar

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#348]
I had previously mentioned that I had trouble with salt plume parametrization and resulting ssh drop. I had another look at the log files and found that it was not SPP that caused the issue, but rather any that any simulation using latest refactoring branches and zstar feature a spurious drop of ssh over time. 
I compare here the log output of a run with the old 2.0 master branch, with log output from [fluxpaper/OCURRF+NOHEM+SPP](https://github.com/FESOM/fesom2/tree/fluxpaper/OCURRF%2BNOHEM%2BSPP) with [fluxpaper/OCURRF+NOHEM+REFAC+SPP](https://github.com/FESOM/fesom2/tree/fluxpaper/OCURRF%2BNOHEM%2BREFAC%2BSPP). The latter had the latest refactoring branch merged in yesterday.

2.0:
```
  0:    ___global estimat of eta & hbar____________________
  0:     int(eta), int(hbar)      =  0.000000000000000E+000  0.000000000000000E+000
```
refactoring:
```
  0:    ___global estimat of eta & hbar____________________
  0:     int(eta), int(hbar)      = -1.000435333167471E-003 -1.000435333167471E-003
```

In particular it seems that the mean water flux is no longer close to zero:
2.0:
```
  0:    ___global min/max/mean  --> mstep=         960 ____________
  0:         wflux= -3.265E-06 |  2.265E-06 | -6.390E-25
```
refactoring:
```
  0:    ___global min/max/mean  --> mstep=         960 ____________
  0:      wflux= -2.008E-06 |  1.692E-06 |  4.758E-10
```

**I wonder, has the default setting of any switch regarding water mass conservation with zstar changed?**

**Comment by patrickscholz** [comment]
Hi Jan 
That would mean that we have somewhere a freshwater source/sink contribution from openifs that we dont seem to balance in FESOM2. Since you drift to negative int(eta) it must be some freshwater flux out of the ocean so something evaporation like. Did you switch something on in openifs that is related the freshwater? I think we have to take appart all the contributions to the total freshwater flux when using openifs and check what we are missing.
Mfg

**Comment by JanStreffing** [comment]
As a first test I set all mass fluxes to 0 in OpenIFS. wflux mean is small now:
`  0:      wflux= -1.335E-06 |  1.754E-06 |  2.556E-24`
int(eta) and int(hbar) are still much larger than before, but they don't grow anymore:
`  0:     int(eta), int(hbar)      = -4.130195205799470E-006 -4.130195205799470E-006`

For comparison, the values used to be constant at:
`   0:        wflux= -2.190E-06 |  1.333E-06 |  1.278E-24`
and
`   0:    int(eta), int(hbar)      =  4.288408092505519E-017  4.288408092505519E-017`
with OpenIFS mass fluxes before I switched to refactoring.

**Comment by patrickscholz** [comment]
Hi Jan 
In principal that is also what i would have done, but set really everything to zero also the mass fluxes that come from the ice, so first make sure that  int(eta), int(hbar) is smaller than 1.0e-16 1.0e-16, so we really balance out the freshwater flux. And from that point on you slowly switch back on one component after another and see when the balancing breaks. At least that was the most systematic way to debug the freshwater issues in icepack. This strategy should also work here. If you have problems with that we can also meet this week at some point. 

As long as  use_cavity=.false. : ocean_area==ocean_areawithcav, so the area should not play a role here. See https://github.com/FESOM/fesom2/blob/e7562dcb1754181492f41e4f664886fba6160562/src/oce_mesh.F90#L2061-L2073

in case use_cavity=.false., mesh%ulevels_nod2D(n) is always 1 !

**Comment by JanStreffing** [comment]
Documenting our webex exchange:

_Hey Jan i just looked a bit through the code...
Can it be that the therm `ice_sublimation(i)= subli` as in `ice_thermo_oce.F90:308` gets lost in the coupled case,
It is added to the evaporation: `evaporation = evap_no_ifrac*(1.-a_ice) + sublimation*a_ice` but it is not added to the variable ice_sublimation that is used in the balancing!_

I set `ice_sublimation = sublimation*a_ice`, but it seems to make the problem worse:

Results after 12 timesteps, without vs. with ice_sublimation.
```
    0:  ___CHECK GLOBAL OCEAN VARIABLES --> mstep=          12                                           |    0:  ___CHECK GLOBAL OCEAN VARIABLES --> mstep=          12
    0:    ___global estimat of eta & hbar____________________                                            |    0:    ___global estimat of eta & hbar____________________
    0:     int(eta), int(hbar)      = -1.660351759684824E-005 -1.660351759684824E-005                    |    0:     int(eta), int(hbar)      = -2.459141244849080E-005 -2.459141244849080E-005         
```
I can also see that sublimation is too small to explain the total mass loss signal. Even if it were the other way round as I had thought. In https://github.com/FESOM/fesom2/blob/9915cbb66e810efa48973f15edf51ee63ec1cc22/src/ice_oce_coupling.F90#L426-L435

The the comment in line 431. Yet in the ice_thermo_cpl, we set:
https://github.com/FESOM/fesom2/blob/9915cbb66e810efa48973f15edf51ee63ec1cc22/src/ice_thermo_cpl.F90#L114-L115

I suspected that sublimation is counted twice, once as sea ice mass loss, and then a second time in the ocean freshwater conservation. I cannot see another place where evaporation is assumed to be evaporation + sublimation. The place mentioned in the comment above (`oce_salt_balance.F90`) no longer exists.

I had expected, that I would not get  int(eta) ~ -0.8. But instead I still got -2.0
```
    0:  ___CHECK GLOBAL OCEAN VARIABLES --> mstep=          12                                           |    0:  ___CHECK GLOBAL OCEAN VARIABLES --> mstep=          12
    0:    ___global estimat of eta & hbar____________________                                            |    0:    ___global estimat of eta & hbar____________________
    0:     int(eta), int(hbar)      = -1.660351759684824E-005 -1.660351759684824E-005                    |    0:     int(eta), int(hbar)      = -2.059746480054204E-005 -2.059746480054204E-005  
```

I will try to follow the ICEPACK coupling approach of turning everything to zero now.

**Comment by patrickscholz** [comment]
Ok Jan 
Its a bit weird, but i think the problem is still sublimation... 
So in reality the ice sublimation should not affect the freshwater flux to the ocean but it should be accounted to the total evaporation. So what happens standalone: 
...We compute the freshwater flux using evaporation (without sublimation) https://github.com/FESOM/fesom2/blob/e7562dcb1754181492f41e4f664886fba6160562/src/ice_thermo_oce.F90#L417-L422
But at the end of subroutine therm_ice we add the sublimation to the evaporation to get the "total evaporation" https://github.com/FESOM/fesom2/blob/e7562dcb1754181492f41e4f664886fba6160562/src/ice_thermo_oce.F90#L447
Since evap is now the "total evaporation", for the balancing we have again to substract the sublimation since sublimation should not contribute to the freshwaterflux in/out of the ocean. https://github.com/FESOM/fesom2/blob/e7562dcb1754181492f41e4f664886fba6160562/src/ice_oce_coupling.F90#L292-L295

So what i think (hopefully) needs to be done, is to delete the sublimation therm in ice_therm_coupl.F90 at that line https://github.com/FESOM/fesom2/blob/e7562dcb1754181492f41e4f664886fba6160562/src/ice_thermo_cpl.F90#L99

and add this term back after the freshwater has been computed, so after the call ice_growth.  
...
call ice_growth
evaporation(inod)       = evaporation(inod)+sublimation(inod)*a_ice(inod)
ice_sublimation(inod) = sublimation(inod)*a_ice(inod)
...

**Comment by JanStreffing** [comment]
Okay with a lot of help from Patrick I was able to reconstruct what I had done to get the mass conservation in the old none refactoring branches, and I reproduced this in the refactoring ones:

```
  0:  ___CHECK GLOBAL OCEAN VARIABLES --> mstep=          57
  0:    ___global estimat of eta & hbar____________________
  0:     int(eta), int(hbar)      = -1.286522427751655E-016 -1.286522427751655E-016
  0:      --> error(eta-hbar)     =  0.000000000000000E+000

```

For AWI-CM3 Patrick found that I had made the following commit about a year ago (that I had since forgotten about): https://github.com/FESOM/fesom2/commit/cb2add54a86f9478d702d9e287a70f57b88defa0

As you can see, instead of adding up the A->O fluxes excluding sublimation, I instead take water_flux from ice_thermo_cpl.

This variable gets here as:
```
fresh_wa_flux => ice%flx_fw(:)
water_flux(n)  = -fresh_wa_flux(n)
```
Not the the negative! And comes from ice_thermo_cpl.F90:
```
fresh_wa_flux => ice%flx_fw(:)
fresh_wa_flux(inod) = fw
```
with
```
fw = PmEocn*rhofwt - dhgrowth*rhoice - dhsngrowth*rhosno
```
where
```
PmEocn = PmEocn + PmEice
```
and
```
PmEice = A*snow + A*subli
PmEocn = rain + runo + (1._WP-A)*snow + (1._WP-A)*evap
```

So conceptually:
water_flux = -Rain - Runoff - OceSnow - OceEvap - IceSnow - IceSubl - IceGrow - SnowGrow

I calculate flux by adding + IceGrow + SnowGrow to eliminate the sea ice melting / growing. I do not eliminate IceSubl  (looking at the previous implementation here):
https://github.com/FESOM/fesom2/blob/5234f38358b8b5f98f09b189ed86e3e146ab2cc3/src/ice_oce_coupling.F90#L294
Finally I also changed the sign of the net correction:
https://github.com/FESOM/fesom2/blob/5234f38358b8b5f98f09b189ed86e3e146ab2cc3/src/ice_oce_coupling.F90#L317

When I do the equivalent to that in the refactoring branch, I also get 0 ssh change with time there. The questions are:
a) Does was this correct procedure for the old branches / AWI-CM v3.0
b) How does this differ from the procedure implemented thus far. / Why does the old procedure not work for AWI-CM3.

**Comment by JanStreffing** [comment]
After talking about this with @dsidoren, he thought that the idea of drawing the line between the systems between sea ice and atmosphere, rather than the old implementation of drawing it between sea ice and ocean was a good one.

```
Mass flux over this boundary is conserved:

Atmosphere
----------- <- My implementation
Sea ice
----------- <- Default implementation
Ocean
```

And that this should also work for FESOM2 standalone. @patrickscholz can you try this out?

**Comment by patrickscholz** [comment]
Meine Erfahrung aus FESOM2 standalone ist, das ohne Einbeziehung der Eis und Snow growth rates bei zstar das Modell allmählich davon drifted ...
