### ISSUE TITLE
Separating calving from river runoff

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#36]
I added a functionality to OIFS 43 that can distinguish river runoff (Precipitation - Evaporation - Soil storage - Snow layer change) from "calving". Calving in this context is a very simple process by which the accumulating snow that would exceed the maximum snow layer thickness (10m) of the HTESSEL hydrology model is send to a simple routing algorithm and discharged into the ocean.

Think of it as solid instead of liquid river discharge. The idea is to add this mass flux to the sea ice thickness. Thereby the latent heat of melting would be incorporated into the coupled system. My first, probably naive, thought would be to divide the massflux (m³/s) of calving/ice discharge by the discharge area (m²). Then multiply by the timestep (s) and add the resulting value (m) to sea ice thickness here:
https://github.com/FESOM/fesom2/blob/b149e61c76a136d36d2fa8f40ad180db1cd7afb5/src/ice_thermo_cpl.F90#L312-L313
Does this sound plausible to you? Perhaps you can also illuminate how it's done in AWICM1 & 2? Does this all happen on ECHAM6 side?

**Comment by JanStreffing** [comment]
Note: A significant fraction of the freshwater stored in Glaciers is released through basal melting rather than calving. This change would include the basal melt flux as calving/sea ice release with the current idea.

I made a back of the envelope calculation for magnitude of the heat flux required to melt the annually accumulating snow.

- Antarctica: 
  - Mean precipitation: Assume ~50 [mm/year] water equivalent. Making it easy, no liquid runoff.
  - Area: 14.200.000 [km²]
    0.05 [m/y] * 14,2*10¹²[m²] = 0,71*10¹² [m³/y] = ~22500 [m³/s] = 22,5*10⁹ [g/s]
    E = 22,5*10⁹  [g/s] * 333,55 [J/g] = 7,5 *10¹² W

- Apply this flux to area of mean Antarctic sea ice extend:
  - Area: ~10⁶ [km²] = 10¹² [m²]
    F =  7,5 *10¹² [W] / 10¹² [m²] = 0,75 [W/m²]


Note, that Greenland has much higher precipitation/area than Antarctica, although here we also see surface melt and surface runoff. According to https://doi.org/10.5194/tc-14-3935-2020 snowfall is about evenly split into runoff and accumulation. 
- Taking their value of SMB: 338 [GT/y]
  - 338 [GT/y] = 10,7*10⁹ [g/s]
    E = 10,7*10⁹  [g/s] * 333,55 [J/g] = 3,6 *10¹² W
  - Area of Greenland ~2*10⁶ [km²] -> factor 7 smaller than Antarctica. -> I also assume factor 7 smaller melting area on the ocean -> 1,4 *10⁶ [km²]!
    F =  3,6 *10¹² [W] / 1,4 *10¹² [m²] = 2,5 [W/m²]

For comparison, annual mean long-wave heat flux from the ocean into the air is ~45 W/m² around Antarctica and in the Labrador Sea. We had about 1[K] sensitivity to ~5-10 [W/m²] SW downward flux correction from http://doi.org/10.21957/s41h7q7l in the Southern Ocean. I would expect changes in the SST on the order of magnitude ~0,1 - 0,4 [K]. These changes would go in the right direction. Compare with:  https://doi.org/10.1029/2019MS001696

> <img src="https://user-images.githubusercontent.com/25483665/100652762-b0647400-3347-11eb-9860-814b8a9ab7e4.png" width="300" height="200"> 

-> **It's probably worth following up on this idea.**

**Comment by JanStreffing** [comment]
As discussed with Christian Rodehacke, a better implementation is to keep adding the freshwater flux as a liquid and instead generate a heat flux from the fraction of the mass-flux that should be solid. This solves issues of water and salt conservation and simplifies the idea to it's essence.

**Comment by JanStreffing** [comment]
While implementing this I found that the solid runoff was not being send properly. It was given to the runoff mapper but not added up to the total runoff. The resulting new coupling contains both the solid freshwater-flux as well as the resulting heat-flux from melting said freshwater.

Shown here is the impact on a 10 year comparison run with TL159L60-CORE2.

Runoff Old -> New
<img src="https://user-images.githubusercontent.com/25483665/105328361-42625d80-5bd0-11eb-83b0-5644290fef38.png" width=49% height=49%> <img src="https://user-images.githubusercontent.com/25483665/105329247-3a56ed80-5bd1-11eb-9ecb-e1974f11278f.png" width=49% height=49%>

SSS Old -> New
<img src="https://user-images.githubusercontent.com/25483665/105329497-830ea680-5bd1-11eb-8df4-42e43e787b77.png" width=49% height=49%> <img src="https://user-images.githubusercontent.com/25483665/105329514-86099700-5bd1-11eb-9d95-105d5f702d0f.png" width=49% height=49%>

SST Old -> New
<img src="https://user-images.githubusercontent.com/25483665/105329608-9de11b00-5bd1-11eb-8dfe-13cc5fd12099.png" width=49% height=49%> <img src="https://user-images.githubusercontent.com/25483665/105329623-a20d3880-5bd1-11eb-86ec-9a6da23a4ad6.png" width=49% height=49%>


Heat flux from solid runoff melt only via OASIS for now. Will follow as proper FESOM2 output in a while.

**Comment by crodehacke** [comment]
Dear Jan,

Good catch. Great that you found this bug. Since I still work with an older version where this bug may haven't been found, which code part shall I inspect to verify that it works?

**Comment by JanStreffing** [comment]
You mean ECE-3?

**Comment by crodehacke** [comment]
I'm talking about the original ECE (Version 3.3), which you can fetch from the EC-Earth's community SVN. I'm in progress to finalize the coupling between ECE and the Parallel Ice Sheet Model representing Antarctica. As in AWI-CM, we want to use the hydrological routing to distribute the freshwater coming from the ice sheet model in the initial configuration. Later, we may transfer ocean-related flux directly into the ocean while keeping the hydrological routing for everything else. Once our technical report is published, I'll share a link to the report.

**Comment by JanStreffing** [comment]
ECE-3 does not have the runoff bug. I'm unsure if they have a heat flux based on the soild part.

**Comment by trackow** [comment]
Great to see this being implemented in a more consistent way! I am still wondering how much Sv the "excess snow" usually amounts to per year after you fixed the bug? Is this now anywhere in the region of 1500 Gt/year (something around 0.05Sv or so, you checked this once?) or is observed calving actually still much higher than what the excess snow in the model would imply? 

This would ask for a sensitivity study with higher calving as observed (to see the impact), and some kind of meltwater forcing scenario (https://doi.org/10.1038/s41558-019-0546-1) for projections. We can leave this to me if my proposed project goes through :)

**Comment by crodehacke** [comment]
"Depoorter et al. (2013) reported a nearly equal share between calving (1321±144 Gt yr−1) and basal melting (1454±174 Gt yr−1) in the period between 1995 and 2009; Rignot et al. (2013) detected a slightly higher contribution from basal melting (1325±235 Gt yr−1 compared with calving with 1089±139 Gt yr−1) between 2003 and 2008; and Liu et al. (2015) found that the basal melting (1516±106 Gt yr−1) contribution was twice as much as the calving (755±24 Gt yr−1) contribution (2005–2011)." as found in HTTP://dx.doi.org/10.5194/esd-11-1153-2020
