### ISSUE TITLE
Error compiling FESOM2 with GCC 6.4.0

### ISSUE THREAD

**Issue by uwefladrich** [FESOM/fesom2#373]
Building FESOM2 with GCC 6.4.0, I get these errors:
```
[...]/fesom2/src/cpl_driver.F90:211:59:

      integer                    :: counts_from_all_pes(npes)
                                                            1
 Error: Automatic array ‘counts_from_all_pes’ at (1) cannot have an initializer
[...]/fesom2/src/cpl_driver.F90:212:59:

      integer                    :: displs_from_all_pes(npes)
                                                            1
 Error: Automatic array ‘displs_from_all_pes’ at (1) cannot have an initializer
```

I found [this bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59537) (somewhat older), which seems to apply to the situation. Following the information in the report, I removed `-finit-local-zero`from `src/CMakeLists.txt` and sure enough, it compiles. Note that even a somewhat newer version (8.2.0) is mentioned, so a wider range of GCC versions might be affected and consequently FESOM2 cannot be build with this versions.

While it is a bit unclear if the whole thing is to be considered a GCC bug, it might be possible to easily avoid the issue altogether. The code in `cpl_driver.F90` contains a number of "catch-all" `save` statements in the subroutines, which seems to be overkill anyway (GCC also warns about "duplicate SAVE attributes"). In fact, the variables above are not _explicitely_ `save`'d, it's just by means of the general `save` statement in the subroutine. Reconsidering if a general `save` is really needed could circumvent the GCC issue (regardless whether it is a bug or not) and improve the code by avoiding unnecessary saved variables.

PS: Using `--finit-local-zero` as a default setting could be another issue to discuss.

**Comment by uwefladrich** [comment]
I realise that this issue relates to the `master` branch.

**Comment by koldunovn** [comment]
@uwefladrich thanks a lot for reporting this! Fixing it in the master would not be priority, as we plan to have it updated sooner rather than later. The current branch that contains all latest developments called `refactoring`.
