### ISSUE TITLE
Execute_command_line error on albedo

### ISSUE THREAD

**Issue by BuffbelliedHummingbird** [FESOM/fesom2#397]
For some ensemble sizes and some ensemble members, my FESOM-PDAF run crashes after reading the mesh with "`forrtl: severe (124): Invalid command supplied to EXECUTE_COMMAND_LINE`".

The command is in oce_mesh.F90:
`call execute_command_line("md5sum "//trim(MeshPath)//"nod2d.out | cut -d ' ' -f 1 > "//trim(ResultPath)//"mesh_checksum")`

This happens on Albedo only for some ensemble sizes (e.g. 11 or 18) and only for some of the ensemble members. And it looks like there is plenty of free memory (e.g. free: 237576, inactive: 8128, active: 76) seconds before.

I don't understand it but I can use a different ensemble size :)

**Comment by koldunovn** [comment]
@BuffbelliedHummingbird can you try to comment the whole `if` statement after
```mesh%representative_checksum = '                                '  ```
and before 
```call MPI_BCAST(mesh%representative_checksum, len(mesh%representative_checksum), MPI_CHAR, 0, MPI_COMM_FESOM, MPIerr)```
and see if it works?

@hegish can you please have a look?

**Comment by BuffbelliedHummingbird** [comment]
Thank you @koldunovn !
yes, it works if all of it is commented! it then prints no checksum and continues.
Sorry for the late reply, as the error simply did not happen again for some time.
