### ISSUE TITLE
add env for levante

### ISSUE THREAD

**Issue by suvarchal** [FESOM/fesom2#403]
I am surprised that there is no env file for levante in master and refactoring branches. mistral paths are not applicable for levante so that is no go or am i missing some thing.

**Comment by pgierz** [comment]
I don't think you're missing something. Either someone did not check there code in, or forgot to make a pull request. Has no one run fesom 2 on levante yet? I find this extremely difficult to imagine. Unfortunately all of my users are in the esm-tools club, and there has been levante support in that project since April last year, but that is a different runtime environment...

**Comment by PengyangSong** [comment]
My change in `fesom2/configure.sh` is below
 ```
git diff configure.sh
-source env.sh # source this from your run script too
+source env.sh levante\.atos\.local
+#source env.sh # source this from your run script too
```

**Comment by pgierz** [comment]
Hi Pengyang, thanks. Could you put your changes into a branch and make a pull request? If you are not allowed, you can make a fork. Alternatively, I have admin access in the FESOM 2 repository and could add you to the respective list.

**Comment by PengyangSong** [comment]
Hi @pgierz  and @suvarchal ,
I think this is some small bug I found before Christmas, when I just moved to levante.
Today I tried below and it works:
```
module load git
git clone https://github.com/FESOM/fesom2.git fesom2_test
cd fesom2_test/
git switch refactoring
bash -l configure.sh
```

Either the env in levante or the refactoring branch had some problem in a few days before. It complained that some files are not found so I added that line.

To sum up, please try again now.

**Comment by koldunovn** [comment]
I see the levante file in refactoring `https://github.com/FESOM/fesom2/tree/refactoring/env/levante.dkrz.de` or you need something different? 
The problem might be that you use slightly older version of the code, that did not have this PR #394
