### ISSUE TITLE
allocatable character

### ISSUE THREAD

**Issue by dsidoren** [FESOM/fesom2#407]
https://github.com/FESOM/fesom2/blob/5baae1788b02a56354a26ff90908d5c7560437d9/src/io_netcdf_file_module.F90#L8

As noticed by @trackow ftn cray compiler does not like it and requires static allocation. We need to do it static or come up with an alternative solution the earlier the better @hegish

**Comment by koldunovn** [comment]
I would say we urgently need a version of refactoring that works with lumi version of ftn...
