### ISSUE TITLE
mesh partitioner or fesom_ini does not compile with gnu

### ISSUE THREAD

**Issue by suvarchal** [FESOM/fesom2#446]
I tested this on levante and my local machine, using GNU 11.2.0 it throws

```
......./src/gen_modules_partitioning.F90:536:19:

  534 |      call MPI_SEND(myDim_nod2D,   1,            MPI_INTEGER, 0, 0, MPI_COMM_FESOM, MPIerr )
      |                   2
  535 |      call MPI_SEND(myDim_elem2D,  1,            MPI_INTEGER, 0, 1, MPI_COMM_FESOM, MPIerr )
  536 |      call MPI_SEND(myList_nod2D,  myDim_nod2D,  MPI_INTEGER, 0, 2, MPI_COMM_FESOM, MPIerr )
      |                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
....../src/gen_modules_partitioning.F90:537:19:

  534 |      call MPI_SEND(myDim_nod2D,   1,            MPI_INTEGER, 0, 0, MPI_COMM_FESOM, MPIerr )
      |                   2
......
  537 |      call MPI_SEND(myList_elem2D, myDim_elem2D, MPI_INTEGER, 0, 3, MPI_COMM_FESOM, MPIerr )
      |                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
```

it is puzzling because mesh part is not MPI dependent and compilation of whole model works with GNU compiler, why is the issue only with mesh partitioner.

**Comment by koldunovn** [comment]
The compilation with GNU works in Actions, so probably some levante specific thing.

**Comment by suvarchal** [comment]
> The compilation with GNU works in Actions, so probably some levante specific thing.

not sure what version of compiler is used in the container, i guess less then 10, issue happens for main model too if we remove these lines: 
https://github.com/FESOM/fesom2/blob/21470c4bb27ac9fc090ea4122bbef9a27c9ac2c0/src/CMakeLists.txt#L167-L169

apparently gnu 10+ is pedantic but then not sure if this is a good way to ignore type mismatch, may be more because we ignore types by using `include mpif.h` in mod_partit.f90. making a PR to fix this.

**Comment by koldunovn** [comment]
Here is what we have in the container:

```
root@7c182d92ae62:/fesom# gfortran --version
GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by suvarchal** [comment]
> Here is what we have in the container:
> 
> ```
> root@7c182d92ae62:/fesom# gfortran --version
> GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

makes sense my machine has 11.2 and in levante module too with
``` 
if(CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10 ) 
    target_compile_options(${PROJECT_NAME} PRIVATE -fallow-argument-mismatch) # gfortran v10 is strict about erroneous API calls: "Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)" 
 endif() 
``` 
it works.
