### ISSUE TITLE
Docker benchmark job doesn't report timings: Expected or Unexpected?

### ISSUE THREAD

**Issue by bnlawrence** [FESOM/fesom2#471]
Hi

(thanks very much for providing a docker installation for initial testing)

Not sure if this is known issue, but I just tried the docker (**) install/run-test instructions from readthedocs, on two Mac platforms (Intel and M1Max). In both cases the model appears (*) to have run the test correctly, but in both cases, the timing information reported throughout the benchmarks (i.e. per timestep and in the summary) are full of zeros.

Is no timing information an expected outcome, or do we think this could be an artefact of my environment?

Thanks
Bryan

(*) ok, well I haven't actually looked at the data yet ... so "appears" is a bit of stretch.
(**) I intend to try installing Fesom2 natively on apple silicon as it runs like a dog under emulation ... do you know if anyone has tried Fesom2 on apple silicon?

**Comment by koldunovn** [comment]
Hi @bnlawrence . In testing environment (for sure on my Mac and in [GitHub actions](https://github.com/FESOM/fesom2/actions/runs/5276753190/jobs/9543892539#step:8:950)) the times are not reported (all zeros). So this is:
* known issue
* Something that does not bother us enough to fix it yet :)

**Comment by bnlawrence** [comment]
Cool. Just thought I'd ping you in case.
