### ISSUE TITLE
Suggestion to make refactoring branch the main branch.

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#474]
I was wondering if there are plans to make the refactoring branch the default branch. If not, why? I think we have been using it as a de facto main branch for some time already and it does not seem limited to technical changes anymore.  The last commit on master was a year ago, which makes our repo look dead at first glance. Inspired by #473

**Comment by patrickscholz** [comment]
I think we already discussed between Nikolay, Dima and me to make a real fesom2.6 release event and make then the refactoring branch the new master branch. We just need to find an agreement about the time schedule and see which open pull request are still crucial and need to be merged and to clean up the repository a bit in general. I think biggest problem in moment is to find the necessary time for that task.

**Comment by JanStreffing** [comment]
@koldunovn When would you have time to do it. Should not take more than 3 minutes. 10 if done with great care.

**Comment by JanStreffing** [comment]
Done. We have a new main branch. We did not rename but rather branch off. All new branchings that are supposed to be merged back for long term use shall happen from main now.
