### ISSUE TITLE
Error of surface stress and surface velocity in io_meandata.F90

### ISSUE THREAD

**Issue by XinyueLii** [FESOM/fesom2#538]
Dear Sir or Madam,

We found there are errors in io_meandata.F90, you might consider to change them.
**1.** (Line 431)      'call def_stream(elem2D, myDim_elem2D,   'v_surf',     'surface velocity',                 'm/s', **u_surf**(1:myDim_elem2D),        1, 'm', i_real4, mesh)'

This should be, 'call def_stream(elem2D, myDim_elem2D,   'v_surf',     'surface velocity',                 'm/s', **v_surf**(1:myDim_elem2D),        1, 'm', i_real4, mesh)'

**2.** (Line 434,435) '     if (sel_forcvar(11)==0) call def_stream(elem2D, myDim_elem2D,   'tx_sur',     **'zonal wind stress to ocean'**,     'm/s2', stress_surf(1, 1:myDim_elem2D),1, 'm', i_real4, mesh) ; sel_forcvar(11)=1
     if (sel_forcvar(12)==0) call def_stream(elem2D, myDim_elem2D,   'ty_sur',     **'meridional wind stress to ocean'**,'m/s2', stress_surf(2, 1:myDim_elem2D),1, 'm', i_real4, mesh) ; sel_forcvar(12)=1
'

This might not be just wind stress... should be wind+ice (total stress), cause in 'ice_oce_coupling.F90', we found'        stress_surf(1,elem)=sum(stress_iceoce_x(elnodes)*a_ice(elnodes) + &
                                stress_atmoce_x(elnodes)*(1.0_WP-a_ice(elnodes)))/3.0_WP
        stress_surf(2,elem)=sum(stress_iceoce_y(elnodes)*a_ice(elnodes) + &
                                stress_atmoce_y(elnodes)*(1.0_WP-a_ice(elnodes)))/3.0_WP
'

Thanks,
Xinyue

**Comment by patrickscholz** [comment]
In which branch is this?

**Comment by XinyueLii** [comment]
1. is in the default branch, (I found the u_surf and v_surf just gone after refactoring, you could just ignore this)
2. is in the default branch & refactoring branch

**Comment by XinyueLii** [comment]
> In which branch is this?

1. is in the default branch, (I found the u_surf and v_surf just gone after refactoring, you could just ignore this)
2. is in the default branch & refactoring branch

**Comment by JanStreffing** [comment]
Should have been fixed for refactoring by: #379

**Comment by XinyueLii** [comment]
> Should have been fixed for refactoring by: #379

oh! 😊 Thanks, I just found this issue has been fixed in the refactoring branch, sorry for asking again... Then just noticed that tx_sur and ty_sur might be wind+ice stress, not just wind💨
