### ISSUE TITLE
Mesh Rotation (or, our never-ending and very favorite "bug") 

### ISSUE THREAD

**Issue by pgierz** [FESOM/fesom2#54]
Hi guys,

I've been working on consolidating the various tools we have for mesh generation and subsequent input creation for ECHAM6/JSBACH. Part of the process runs the Triangle program with a few scripts that Sven Harig has provided for us.

Two questions arise from that:

1) Are the meshes produced by the triangle program rotated or unrotated? How do I determine that?
2) How do I rotate (or unrotate) them? 

From my understanding, the new default should be unrotated (please correct me if I'm wrong)

**Comment by koldunovn** [comment]
1. I don't know what is used by default by Sven's generator, but the version I have produce unrotated meshes (it is made to work with JIGSAW).
2. You can convert from rotated to unrotated (geographical) by using this code python code https://github.com/FESOM/pyfesom2/blob/c591961fc0956b4d488c3c02326ca945b5cba68c/pyfesom2/ut.py#L26 This function will convert them back https://github.com/FESOM/pyfesom2/blob/c591961fc0956b4d488c3c02326ca945b5cba68c/pyfesom2/ut.py#L102 Usually this works just fine, but there are some edge cases when it fails, for example I wasn't able to rotate `pi` mesh with this functions and asked @helgegoessling to do this with his R scripts.

**Comment by koldunovn** [comment]
Ah, and the easiest thing to determine if the mesh is rotated is just to plot it :)

**Comment by koldunovn** [comment]
I can't manage to answer everything in one comment... 
Yes, the default will be unrotated. Have a look at #50 and #52 .

**Comment by hegish** [comment]
How about editing your original comment? 😀

**Comment by koldunovn** [comment]
> How about editing your original comment? 😀

Then we can't pretend that there is a lot of activity in the issues :)

**Comment by hegish** [comment]
Haha. Do you know if editing will also trigger an email notification?

**Comment by koldunovn** [comment]
> Haha. Do you know if editing will also trigger an email notification?

I don't think so :) So this might be justification for spamming messages :)

**Comment by pgierz** [comment]
Ok I'll make some plots to check. Nikolay, if I just run pfplot without any agb arguments, that should give us an answer, right?

**Comment by pgierz** [comment]
More activity is always better 😉 then the bosses will think we are actively working.

However, in seriousness: Nikolay can you, Dima, and the rest of the fesom team let me know where to put my mesh creation stuff? Directly on the fesom repo, or somewhere else? I think it would be nice to check that in...

**Comment by koldunovn** [comment]
> Ok I'll make some plots to check. Nikolay, if I just run pfplot without any agb arguments, that should give us an answer, right?

Yes. But don't forget to remove any `pickle` or `joblib` files you happen to have in the  mesh directory.

**Comment by koldunovn** [comment]
> More activity is always better 😉 then the bosses will think we are actively working.
> 
> However, in seriousness: Nikolay can you, Dima, and the rest of the fesom team let me know where to put my mesh creation stuff? Directly on the fesom repo, or somewhere else? I think it would be nice to check that in...

We can move it to FESOM organization if you are OK with that. I would not ship it with FESOM2, but I think https://github.com/FESOM will be the right place for it.

**Comment by koldunovn** [comment]
@pgierz The suggestion to move to FESOM2 organization, if you wish, is still there :) I will close the issue now, but let me know on how you decide to proceed with mesh generation workflow.
