### ISSUE TITLE
How to switch of momix in a correct way?

### ISSUE THREAD

**Issue by christian-stepanek** [FESOM/fesom2#553]
I noted that the use_momix switch is available in more than one of FESOM2's namelists.

I currently run a simulation where I would like momix to be deactivated, and I do this via the following namelist settings:

```
$ cat namelist.oce
&oce_dyn
[...]
&oce_tra
[...]
    use_momix = .false.
```
Yet, I have been notified - and I did not know about this - that there is also a use_momix switch in namelist.tra:
```
$ cat namelist.tra
[...]
&tracer_phys
    use_momix = .false.
```
What is the difference between these two switches in practice? Which of the two identically named switches overrules the other one? I have set the switch in namelist.oce &oce_tra, but not in namelist.tra &tracer_phys. Does doing so provide a simulation where momix is switched off?

Could you please point me to the documentation for the different switches? Unless I overlooked it, namelist.tra is not covered at all at https://fesom2.readthedocs.io/en/latest/. On the other hand, the use_momix switch in namelist.oce &oce_tra does not appear to be documented either (see https://fesom2.readthedocs.io/en/latest/ocean_configuration/ocean_configuration.html)

**Comment by christian-stepanek** [comment]
I get the impression that the switch in namelist.oce may be a relict and setting it does not lead to any change in the simulation. When you have the time, could @patrickscholz maybe comment on this? Thanks a lot.

**Comment by patrickscholz** [comment]
yes the use_momix switch in namelist.oce is obsolete, during the refactoring it went into namelist.tra --> &tracer_phys. . But in the actual namelist.oce of the refactoring branch there is no use_momix anymore, since quite some time. Maybe your namelist.oce is from an older FESOM2 version?

**Comment by christian-stepanek** [comment]
Dear @patrickscholz, thanks a lot. Then I will reconfigure the simulation. Just to better understand the issue that I am running in:

The problem is that the switches appear not documented at readthedocs. Therefore, based on the source code, I tried to figure out myself how to set the switch. Apparently my interpretation was wrong. I understand that you state that the switch should not be there anymore in namelist.oce. Yet, if this indeed is the case, then I am asking myself why my simulation, where I have set that switch in namelist.oce, does not crash. According to my knowledge of fortran, the model should crash if I try to set via a namelist a variable that is not defined in the code, right? Yet, the simulation runs without any obvious technical problem for multiple hundred years. So it seems that there is at least still a definition of that variable in namelist.oce, or am I wrong?

**Comment by patrickscholz** [comment]
so here is the actual default namelist.oce https://github.com/FESOM/fesom2/blob/refactoring/config/namelist.oce. The parameter is defined in oce_modules.F90 --> MODULE o_PARAM
```
NAMELIST /tracer_phys/ diff_sh_limit, Kv0_const, double_diffusion, K_ver, K_hor, surf_relax_T, surf_relax_S, &
            balance_salt_water, clim_relax, ref_sss_local, ref_sss, &
            use_momix, momix_lat, momix_kv, &
            use_instabmix, instabmix_kv, &
            use_windmix, windmix_kv, windmix_nl, &
            use_kpp_nonlclflx
```
... and read in via namelist.tra in gen_model_setup.F90 --> subroutine setup_model(partit)
``` 
  nmlfile ='namelist.tra'    ! name of ocean namelist file
  open (newunit=fileunit, file=nmlfile)
  read (fileunit, NML=tracer_phys)
  close (fileunit)
```
... The reason why your code doesnt complain could be ...  I think fortran scans for this namelist section headers (read (fileunit, NML=**tracer_phys**)) and checks which variables are defined within this header. If in this namelist header section is a variable that is not defined for this header (NAMELIST /tracer_phys/ diff_sh_limit, ...), than fortran should complain for sure! In your case we do not scan anymore for this namelist header **oce_tra** in namelist.oce in this section can stand what ever it wants, the model never tries to look into it and thus can not complain about it!

**Comment by christian-stepanek** [comment]
Thanks a lot @patrickscholz
