### ISSUE TITLE
output files should be separate from input files

### ISSUE THREAD

**Issue by sebastianbeyer** [FESOM/fesom2#617]
Hey,
as we started discussing during the retreat, I would like if the output files of FESOM were different from the inputs. 
This would make handling the runs easier in many cases, e.g. we would not need to copy the initial/restart files for every new run that we do. Also for runs that failed at some point we could simply delete the outputs and start from the same inputs again, so the model is always behaving the same for the same way of configuration/namelist. 
We would need to set the input and output folders via namelist parameters then, I guess.

**Comment by JanStreffing** [comment]
We already had a more extensive discussion on this here: https://github.com/FESOM/fesom2/issues/279. IMO we should continue there.
