### ISSUE TITLE
restart problems with step_per_day=288

### ISSUE THREAD

**Issue by ackerlar** [FESOM/fesom2#68]
Dear all,

I get a restart problem with the standalone version of FESOM2 when setting `step_per_day=288`.

```
  0:  associating restart file /work/ollie/lackerma/awicm_pism_tests//fesom_esm_t33/run_18500201-18500228/work/fesom.1850.oce.restart.nc
  0:  WARNING: all dates in restart file are after the current date 
  0:  reading restart will not be possible !
  0:  the model attempted to start with the time stamp =      2676600
  0:  current restart counter =            1    
  0:  error counter=           9    
  0:  Error: Unknown Error                                                                        
  0:  Run finished unexpectedly!
```
`ncdump -v time` gives `time = 2678100`

A run with the same settings except `step_per_day=48` is working fine and `ncdump -v time` gives `time = 2676600`
(/work/ollie/lackerma/awicm_pism_tests/fesom_esm_t32)

I am using the fesom `master` branch on `commit cc4c49bf71f62ca311954b1681a10bac636e98b6` and the esm_tools
```
+---------------------+-------------+---------------------------------------------------------+------------------+---------------------------+
| package_name        | version     | file                                                    | branch           | tags                      |
|---------------------+-------------+---------------------------------------------------------+------------------+---------------------------|
| esm_calendar        | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_database        | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_environment     | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_master          | 5.0.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_motd            | 5.0.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_parser          | 5.0.3       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_pism            | 0.0.1.dev12 | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_plugin_manager  | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_profile         | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_rcfile          | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_runscripts      | 5.0.14      | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
| esm_tools           | 5.0.11      | /home/ollie/lackerma/esm_tools                          | iceberg_coupling | v5.0.11-13-ge41ee3a-dirty |
| esm_version_checker | 5.1.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                  |                           |
+---------------------+-------------+---------------------------------------------------------+------------------+---------------------------+
```
I am not sure this issue is more FESOM2 or esm_tools related.

**Comment by koldunovn** [comment]
The problem you have is probably related to `fesom.clock` file, that determine when the model will start. 

What is the content of your `fesom.clock` file, when you try to run with smaller time step?

**Comment by koldunovn** [comment]
What I currently see in `/work/ollie/lackerma/awicm_pism_tests//fesom_esm_t33/run_18500201-18500228/work/` is that `fesom.clock` and restart files are not consistent. The `/work/ollie/lackerma/awicm_pism_tests//fesom_esm_t33/run_18500201-18500228/work/fesom.1850.oce.restart.nc` implied that it was created with 5min time step. The `/work/ollie/lackerma/awicm_pism_tests//fesom_esm_t33/run_18500201-18500228/work/fesom.clock` tries to run from restart created with 30m timestep. 

More info on `fesom.clock`: https://fesom2.readthedocs.io/en/latest/getting_started/getting_started.html#the-clock-file

**Comment by pgierz** [comment]
In the esm-world the clock file is generated for you "on the fly", see here:

https://github.com/esm-tools/esm_tools/blob/588bd5000a1b1df9074738a7cc6cbe17ed7d2eb7/configs/components/fesom/fesom-2.0.yaml#L194-L204

Corresponding code to actually use that:

https://github.com/esm-tools/esm_runscripts/blob/a81137fd8f9c4a4b41118c178373e6ee40e45262/esm_runscripts/compute.py#L116-L140

Maybe that helps further... if not, let one of the esm-tools guys know (@dbarbi, @mandresm, or @denizural)

**Comment by pgierz** [comment]
OK, the problem is here:
lasttime: "$(( 86400 - ${time_step}))"

Thats a few lines further up in the fesom yaml. If you start fesom with a different timestep, that won't work. We can provide a workaround for that though...

**Comment by ackerlar** [comment]
Thank you for the fast response! An easy workaround is to set `time_step` in the *yaml file (`/work/ollie/lackerma/awicm_pism_tests/fesom_esm_t34/scripts/fesom2-cav-monthly.yaml`). The restart worked fine. But I guess, to set `time_step` and `step_per_day` in the *yaml file is a bit redundant. I will close this is issue here and rather open an issue for the esm_tools.

**Comment by mandresm** [comment]
@ackerlar , I'll have a look at it, as I am currently working with the fesom2.yaml

**Comment by ackerlar** [comment]
I just recognized that `step_per_day` is set by esm_tools according to `time_step`, so it's actually enough to set `time_step` inside the FESOM section of the *yaml file (`/work/ollie/lackerma/awicm_pism_tests/fesom_esm_t35/scripts/fesom2-cav-monthly.yaml`).

**Comment by mandresm** [comment]
ah! you're right! Good to know :)
