### ISSUE TITLE
Latest FESOM2 not working with esm-tools

### ISSUE THREAD

**Issue by PengyangSong** [FESOM/fesom2#69]
Dear developers,
I am running some cases using esm-tools but it is not working with the latest version.
The log says:
 4:  error in line          549 io_meandata.F90 NetCDF: File exists && NC_NOCLOBBER
 4:  error in line           97 async_threads_module.F90
Maybe the esm-tools is not working with async_threads_module?
which package does this require? or can I disable this approach in FESOM2?
Many thanks.

**Comment by denizural** [comment]
Hi @PengyangSong,
could you please provide the path of your runscript then we can have a look.
Best,
Deniz

**Comment by koldunovn** [comment]
Hi @PengyangSong 

Can you paste here more details on the error here?

**Comment by PengyangSong** [comment]
Thanks @denizural  and  @koldunovn .
I checked again the settings and found that with all the original settings, the model is running good.
But when I set 'ldiag_energy =.true.' (in namelist.io), the error occurs.

The location of logs: /work/ollie/psong/FESOM2/fesom2_NOTIDE5/scripts
The location of config: /home/ollie/psong/esm-tools/esm-master/fesom-2.0/config_notide5
The location of src: /home/ollie/psong/esm-tools/esm-master/fesom-2.0/src

Note that I changed all variables in ldiag_energy to annual mean output (src/io_meandata.F90).

**Comment by koldunovn** [comment]
Maybe the reason is that you try to use `Av` output from the standard output and from energy diagnostics? try to remove `Av` from `namelist.io`. We should avoid to have the same names in `namelist.io`, I will try to take are of it.

**Comment by PengyangSong** [comment]
@koldunovn You are right. However, it is kind of weird because the same setting without using esm-tools will not leading to this error.
Thanks a lot.

**Comment by denizural** [comment]
@PengyangSong
you can also view the namelist that esm-tools uses by giving the `-v `(verbose) option to the `esm_runscripts`. Or of course from your work directory.
