### ISSUE TITLE
Makefiles, can we clean them up?

### ISSUE THREAD

**Issue by koldunovn** [FESOM/fesom2#73]
Currently we have a lot of old Makefiles hanging around. In the root we have:
```
Makefile
Makefile.in
Makefile.in_dkrz
Makefile.in_hlrn3_crayintel
Makefile.in_ollie
```
In the `src`:

```
Makefile
Makefile_hlrn
Makefile_ollie
```
And also folders `dkrz`, `hlrn` and `ollie`. 

Can we delete some of them? @rakowsk I know you are using Makefiles, maybe someone else?

**Comment by rakowsk** [comment]
The Makefile in upper level directories now all source the Makefile.in in root. Thus, on any other level, Makefile.in should be obsolete - really! :-)

Makefile.in should not be in git, as it is changed depending on the system you are on.

Makefile.in_dkrz, _ollie, _hlrn should also no longer be needed, however, Makefile.in_intel, _gcc, _nvidia and so on are of interest (for me, and maybe benchmarkers).  

I can do this cleaning in landmask.

**Comment by koldunovn** [comment]
Natalja, thanks for the info!
Can you, please, do the cleaning in a separate PR, it's really painful to merge many changes at once. Or just give me the list of the files to delete and I can do it by myself.

**Comment by koldunovn** [comment]
Close via #72
