### ISSUE TITLE
Running sequentially (on 1 processor)

### ISSUE THREAD

**Issue by dguibert** [FESOM/fesom2#84]
Is it possible to run FESOM on 1 processor?
In `fvom_init`, it is not possible to generate a dist_1 directory. Can we disable this to run/profile on 1 processor, will `fesom` be ok?

**Comment by rakowsk** [comment]
Most probably, it will not work. In principle, the MPI is encapsulated with "if (npes>1)", however, there will be too many exceptions, I am afraid. At least for my part, when working on FESOM, I never tested on just 1 processor, and I never carefully considered this case. If FESOM could really run in serial, it would not need any dist_1 directory, as the dist directories only contain information on the domain decomposition.

For a moment, I was considering to give it a try, but I am afraid that it will take a lot more than one day to make it work. 
Maybe, it could be easier to regard just a part of the code and feed it with the required fields for one timestep. Which part do you have in mind (tracers?), and which problem size?

**Comment by koldunovn** [comment]
@dguibert If you want it for testing, maybe running on just several cores is OK for you? I think it's hard to find processor with only one core nowadays, and running with with `dist_2` is no problem for fesom (regularly do it with pi mesh).

**Comment by dguibert** [comment]
Ok. Thanks for your answers.
I'll start the scaling profiling at 2 npes.
