### ISSUE TITLE
Inconsistent dimension names in mesh diag and model output 

### ISSUE THREAD

**Issue by suvarchal** [FESOM/fesom2#87]
Variable (dimension) names that represent same fields in model output and mesh diagnostics are named differently. Apart from consistency reason, having a same naming convention, will simplify post-processing and probably also make it easier for a new FESOM data user to understand.

I don't know of any plans to standardize names but I think at minimal, using same dimension names in mesh diag as in model data is useful.

for instance associations of names in mesh diagnostics to model data:

	nod_n  -> nod2
	elem_n -> elem
	nl -> nz
	nl1 -> nz1 

and I think, these level variables may be named same as dimension names harmlessly.

```
Zbar -> nz
Z -> nz1
```
I don't know if mesh diag file is used for restarts? and renaming may pose other challenges?

**Comment by koldunovn** [comment]
@suvarchal thanks a lot, I will try to have a look. Since we probably have to mess with `fesom.mesh.diag.nc` anyway, maybe we have to add some other variables to it? Please have a look at mesh setup in this file for possible options:

https://github.com/FESOM/fesom2/blob/9d38f55e724660c7c4694ffa7e80d0e9e5b0f9c9/src/MOD_MESH.F90

**Comment by suvarchal** [comment]
I really like current variables in `fesom.mesh.diag.nc` and think that they would make many parts of current post-processing in pyfesom2 simpler and efficient. Right now, I am at a state where I mostly used triangulation information in 2D. I think I can get better perspective on other variables then mentioned above when i use them in near future, for instance using for computing gradients or interpolations.

Meanwhile, one thing that occurs to me is to declare all variables that contain indices as 32-bit unsigned int, and with a range about 4+ billion should be enough at least for a few years?, and can reduce the size of mesh file significantly.

**Comment by koldunovn** [comment]
@helgegoessling Helge, will such changes break things in spheRlab?

**Comment by koldunovn** [comment]
@suvarchal Turns out FORTRAN does not support unsigned integers, so better not to experiment with this :)

**Comment by helgegoessling** [comment]
> @helgegoessling Helge, will such changes break things in spheRlab?

The changed variables are not used in spheRlab, so no problem. Thanks for checking :-).

**Comment by hegish** [comment]
> @suvarchal Turns out FORTRAN does not support unsigned integers, so better not to experiment with this :)

But netCDF does. It is certainly possible to write unsigned int from Fortran, too.

**Comment by koldunovn** [comment]
@hegish How would one do this? I tried to find fortran netCDF types for unsigned ints and failed :)
