### ISSUE TITLE
MPI routine used before intialization of MPI, for coupled setups in ALEPH

### ISSUE THREAD

**Issue by mandresm** [FESOM/fesom2#99]
Hi FESOM developers,

@JanStreffing and I are trying to run AWICM3 in ALEPH computer (a Cray system) and we are experiencing some issues involving MPI during run time.

**Branches used**

- FESOM: fesom-2.0-frontiers
- OASIS3MCT: awicm-3-frontiers

**Machine details**

Type: Cray
Batch system: PBS
Scheduler: ALPS (aprun)

**Compilation details**

We are using `ftn` compiler as it is the one recommended by the system admins for Cray. We are also using `mpich`.

**Cases tested**

- FESOM standalone (passes MPI initialization)
- **FESOM coupled** for AWICM3 has the error described below (setting the coupled flags on `FESOM_COUPLED ON` and `OIFS_COUPLED ON`. OASIS libraries are compiled before FESOM and linked).

**Detailed description of the problem**

We are experiencing the following issue during runtime of FESOM coupled in AWICM3:
```
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH
...
Attempting to use an MPI routine before initializing MPICH
[NID 00150] 2021-04-16 20:00:33 Apid 423459: initiated application termination
Fri Apr 16 20:00:33 2021: [PE_120]:inet_recv:inet_recv: recv error (fd=7) Connection reset by peer
Fri Apr 16 20:00:33 2021: [PE_120]:_pmi_network_barrier:_pmi_inet_recv from target 0 failed pmi errno -1
Fri Apr 16 20:00:33 2021: [PE_120]:_pmi_barrier:network_barrier failed
[Fri Apr 16 20:00:33 2021] [c0-0c2s6n1] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(638).......:  PMI2 init failed: 1 
Application 423459 exit codes: 1
Application 423459 exit signals: Killed
Application 423459 resources: utime ~3s, stime ~13s, Rss ~16864, inblocks ~51250, outblocks ~0
```

However, when we run the exact same version of FESOM-2.0 but compiled for standalone we seem to get further, as MPI reports initialization (we run standalone just to narrow down the problem, the crash that happens after MPI intialization is probably related to something we've done wrong in the configuration of the standalone test):
```
 MPI has been initialized, provided MPI thread support level: MPI_THREAD_SERIALIZED 2
 Running on  288  PEs
 
 FESOM2 git SHA: f3c62de
 ^[[32m____________________________________________________________^[[0m
 ^[[7;32m --> FESOM BUILDS UP MODEL CONFIGURATION                    ^[[0m
```

So it seems that the problem we are having is associated to something in the coupling of FESOM and/or in the interaction with OASIS. Has anyone experienced something similar to this? @JanStreffing reported similar problems with Juwels system. Has anyone an idea about what might be going on? @dsidoren 

Kind regards

**Comment by mandresm** [comment]
I forgot to mention, that running only `OpenIFS` with coupled flags on also passes the MPI initialization and start to produce files.

**Comment by JanStreffing** [comment]
Great work closing in the circle on this one. I guess it's all within these few lines on the fvom_main.F90 and how they are dealt with in Oasis:

https://github.com/FESOM/fesom2/blob/a757d9c4c02585b225103963f2b704ae6bd5bfb0/src/fvom_main.F90#L48-L58

We let oasis do the MPI_init for FESOM2. This is the same procedure as in OpenIFS (https://gitlab.dkrz.de/ec-earth/oifs-43r3/-/blob/master/src/cplng/oasis/cplng_init_mod.F90#L42) and the runoffmapper (https://gitlab.dkrz.de/ec-earth/runoff-mapper/-/blob/awicm-3-frontiers/src/cplng/cplng_init_mod.F90#L23), but here it does not work for some reason that eludes me still.

**Comment by mandresm** [comment]
I think the problem might be that `t1 = MPI_Wtime() ` is called before the MPI initialization that for AWICM3 (where `__oifs` is defined), occurs in line 57. Commenting out `t1 = MPI_Wtime() ` allow fesom to continue running past this point.

**Comment by JanStreffing** [comment]
Perfect. The fix could not be simpler. But the way there was quite involved. I moved `t1 = MPI_Wtime() ` behind the second preprocessor declaration. I will include it on the branch https://github.com/FESOM/fesom2/tree/awicm-3-frontiers
